### ISSUE TITLE
""No OpKernel was registered" issue when tried to run resnet_model.py without TPU

### ISSUE THREAD

**Issue by yongcale** [tensorflow/tpu#100]
Using TensorFlow v1.7rc1, tried to run tpu/models/experimental/resnet_bfloat16/resnet_model.py with GPU (without TPU), got "no OpKernel was registered" error.

command to run:
python3 resnet_main.py --use_tpu=False --data_dir=/home/ubuntu/imagenet/train-480px --model_dir=~/model_dir

error info:
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'Conv2D' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]

	 [[Node: cg/conv2d/Conv2D = Conv2D[T=DT_BFLOAT16, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true](cg/Pad, Cast)]]

**Comment by saeta** [comment]
Hi @yongcale,

As far as I know, GPUs and CPUs don't have hardware support for BFloat16. That's why you only have FLOAT, and HALF (FP16) kernels available. I think kernels for the additional platforms could eventually be written, but it might be a little tricky because the hardware is a little different. The TensorFlow team is working on better APIs to handle different mixed precision training on a variety of platforms, so stay tuned for that!

Thanks!
-Brennan

**Comment by RockfordWei** [comment]
@yongcale @saeta I experienced the same issue but I tackled it down but the snippet below - please let me know if it works with your project (check [my ios demo project](https://github.com/RockfordWei/TensorFlow-iOS-Demo-App) for more information):

```
$ bazel build tensorflow/tools/graph_transforms:transform_graph
$ bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=$(PROJECT_DIR)/frozen_inference_graph.pb \
--out_graph=$(PROJECT_DIR)/mobile_inception_graph.pb \
--inputs='image_tensor' \
--outputs='num_detections,detection_boxes,detection_scores,detection_classes' \
--transforms='
  add_default_attributes
  strip_unused_nodes(type=float, shape="1,512,512,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  flatten_atrous_conv
  merge_duplicate_nodes
  remove_device
  strip_unused_nodes
  sort_by_execution_order'
```
