### ISSUE TITLE
Bug in r.27 release tpu/tools/docker/Dockerfile 

### ISSUE THREAD

**Issue by danielvegamyhre** [tensorflow/tpu#1022]
TensorFlow installation is using v2.2.0: https://github.com/tensorflow/tpu/blob/r2.7/tools/docker/Dockerfile#L27

However, it should be 2.7 since tensorlfow/models and tensorflow/tpu are both using 2.7: https://github.com/tensorflow/tpu/blob/r2.7/tools/docker/Dockerfile#L33-L36

**Comment by danielvegamyhre** [comment]
cc @aman2930

**Comment by aman2930** [comment]
Fixed it.
