### ISSUE TITLE
Need Russell's contact info

### ISSUE THREAD

**Issue by bellafeng** [tensorflow/tpu#114]
Hi, Russell,
sorry to contact you this way.
I am the program committee chair of R/Pharma conference. You are highly recommended for giving a talk because of your work for openFDA.  We have been trying to send you the invitation letter but failed with your idione email. Please could you email me at gfeng@amgen.com or bellafeng@gmail.com to get the conversation started?

thank you, 
Bella

**Comment by rjpower** [comment]
Hi Bella, I'll reply offline.
