### ISSUE TITLE
trying the google cloud shell tutorial ...

### ISSUE THREAD

**Issue by ssjohal** [tensorflow/tpu#124]
Solved: I think I've "solved" my problem, by just "Upgrading" my account. So please ignore.

Was:
While trying the google cloud shell tutorial, and having setup a google cloud account, I get:

2018/05/14 15:13:25 googleapi: Error 403: cannot create a TPU Node on a project linked to a free-trial billing account, forbidden

Can someone fix this please and/or tell me what else I can do to make it work? Thanks.

**Comment by saeta** [comment]
Hi @ssjohal : You must set up a billing account in order to access Cloud TPUs. You cannot use Cloud TPUs with the free trial. Hope that helps!
