### ISSUE TITLE
Looking for ImageNet data => TFRecord script

### ISSUE THREAD

**Issue by seansaito** [tensorflow/tpu#134]
In `/resnet_bfloat36/imagnet_input.py`, the documentation refers to the following link for creating TFRecords of ImageNet data: https://github.com/tensorflow/tpu-demos/blob/master/cloud_tpu/datasets/imagenet_to_gcs.py

However, this file does not seem to exist anymore. Where is the script available now?
Thanks.

**Comment by robieta** [comment]
https://github.com/tensorflow/models/tree/master/official/resnet#imagenet

This should get you what you need. We should definitely fix that to point to a real place though. Thanks for reporting.

**Comment by robieta** [comment]
Ah, scratch what I wrote. It looks like the script was just moved:

https://github.com/tensorflow/tpu/tree/master/models/official/resnet#formatting-the-data

**Comment by saeta** [comment]
@robieta is absolutely right; the script is at: https://github.com/tensorflow/tpu/blob/master/tools/datasets/imagenet_to_gcs.py. Thanks @robieta !!

**Comment by seansaito** [comment]
Got it, thanks a lot!
