### ISSUE TITLE
Can U provide an inception v3/v4 model using slim API and support check point for transfer learning

### ISSUE THREAD

**Issue by wildtang** [tensorflow/tpu#157]
I see an inception v3/v4 model using Estimator API has been provided,
Can U provide an inception v3/v4 model using slim API and support check point for transfer learning.
Thank you very much.

**Comment by alope107** [comment]
You can find a non-TPU version of Inception v3 using the slim API here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/nets/inception_v3.py

We are always looking to optimize more models to run on TPUs, but cannot promise that this particular model will be officially ported using the slim API.

If you are looking to port the model yourself it could be helpful to read the "Advanced Guide to Inception V3 on Cloud TPU." It contains an in-depth analysis of the steps taken to optimize the model for TPUs using the Estimator API, much of which may be applicable when porting it in a different manner.
https://cloud.google.com/tpu/docs/inception-v3-advanced
