### ISSUE TITLE
Resnet model doesn't work with no TPU and `use_tpu=false` set.

### ISSUE THREAD

**Issue by mlucy** [tensorflow/tpu#160]
https://github.com/tensorflow/tpu/tree/master/models/official/resnet doesn't appear to work correctly when `--use_tpu=false` is passed.

When I do so (and no TPU is attached to the machine), I get this error:
```
Traceback (most recent call last):
  File "/tensorflow_tpu_models/models/official/resnet/resnet_main.py", line 506, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tensorflow_tpu_models/models/official/resnet/resnet_main.py", line 395, in main
    project=FLAGS.gcp_project)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/cluster_resolver/python/training/tpu_cluster_resolver.py", line 150, in __init__
    self._tpu = compat.as_bytes(tpu)  # self._tpu is always bytes
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None
```

(I'm using Tensorflow 1.9 .)

**Comment by yguo0905** [comment]
Try specifying `--tpu=`.

This is a usability issue that should be fixed in resnet_main.py

**Comment by karandwivedi42** [comment]
Can you try `--nouse_tpu`?

**Comment by karandwivedi42** [comment]
It is a way to do use_tpu=false. "No"use_tpu

**Comment by gitosaurus** [comment]
This will be fixed in an upcoming release, so that `--use_tpu=false` will be sufficient to run on the local CPU. (And as mentioned earlier, `--nouse_tpu` is the same as `--use_tpu=false`.)

**Comment by gitosaurus** [comment]
The fix has been committed to the repository on 2018-08-24.

**Comment by sreenivasmr** [comment]
@gitosaurus @karandwivedi42 @mlotstein 

I am trying to run this

https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/tpu/training/resnet

I am setting the below Flags ... Please note --use_tpu=false

gcloud ml-engine jobs submit training $JOB_NAME \
    --staging-bucket $STAGING_BUCKET \
    --runtime-version 1.9 \
    --scale-tier CUSTOM \
    --module-name resnet.resnet_main \
    --package-path resnet/ \
    --region $REGION \
    --config config_GPU_v100_1_worker.yaml \
    -- \
    --use_tpu=False \
    --data_dir=$DATA_DIR \
    --model_dir=$OUTPUT_PATH \
    --resnet_depth=50 \
    --train_steps=15000 \
    --train_batch_size=256

Please find config_GPU_v100_1_worker.yaml below.

trainingInput:
  scaleTier: CUSTOM
  masterType: large_model_v100
  workerType: large_model_v100
  parameterServerType: large_model
  workerCount: 1
  parameterServerCount: 3

It does not work on the required large_model_v100 GPU, as per the config.

Any help is appreciated.

**Comment by sxs11** [comment]
@yguo0905 @mlucy @mlotstein @karandwivedi42 @bmabey @gitosaurus 
Hi, I try to run https://github.com/tensorflow/tpu/tree/master/models/official/resnet on my own machine and GPU. And I want to run this on GPU with use_tpu=False
All I did is 
export PYTHONPATH="$PYTHONPATH:/path/to/models"
python resnet_main.py --use_tpu=False --model_dir=/tmp/tpu --tpu="" --precision="float32"

but there is an AttributeError: 'module' object has no attribute 'gfile'
Any help is appreciated.(my tensorflow is 1.12)
