### ISSUE TITLE
ctpu go issue

### ISSUE THREAD

**Issue by tadeegan** [tensorflow/tpu#170]
Hi, I followed the instructions for downloading the ctpu tool to use locally but came across this error:

```
./ctpu status
Error encountered while creating configuration: user: Current not implemented on linux/amd64
```

**Comment by saeta** [comment]
@tadeegan can you provide a bit more context about your system? Can you reproduce this in a GCE VM? Does `./ctpu version` work? (If so, what's the output?)

**Comment by tadeegan** [comment]
Nope. ./ctpu version gives the same error.

Its a docker container based on `nvidia/cuda:9.0-devel-ubuntu16.04`

I was able to build ctpu from source and run it.

**Comment by saeta** [comment]
Thanks for the info @tadeegan. I've reproduced the issue and have a fix coming soon!

**Comment by saeta** [comment]
Thanks @aman2930 for the ping!

@tadeegan I believe that with the new `ctpu 1.6` release (available at: <https://dl.google.com/cloud_tpu/ctpu/latest/linux/ctpu> or <https://dl.google.com/cloud_tpu/ctpu/1.6/linux/ctpu>) fixes the issue. If you have a chance, please do test it out and re-open this ticket if the issue still persists. Thanks!
