### ISSUE TITLE
i use gml train object_detection  Have the following error

### ISSUE THREAD

**Issue by uulucky** [tensorflow/tpu#187]
error log
--------------------------------------------------------------
I  master-replica-0 Init TPU system  master-replica-0
I  master-replica-0 Starting infeed thread controller.  master-replica-0
I  master-replica-0 Starting outfeed thread controller.  master-replica-0
I  master-replica-0 Enqueue next (100) batch(es) of data to infeed.  master-replica-0
I  master-replica-0 Dequeue next (100) batch(es) of data from outfeed.  master-replica-0
I  master-replica-0 An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: Socket closed  master-replica-0
W  master-replica-0 

Error occurred during infeed/outfeed.  This may be due to a compile error in the main session.  Waiting for a short time for the main session to come back.

Socket closed  master-replica-0
E  master-replica-0 Feed error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 434, in _run_infeed
    session.run(self._enqueue_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
UnavailableError: Socket closed
  master-replica-0
E  master-replica-0 Closing session.  A RuntimeError should follow.  master-replica-0
I  master-replica-0 Graph was finalized.  master-replica-0
I  master-replica-0 Restoring parameters from gs://storxiaohuaeraicom/tensorflowdata/model.ckpt-0  master-replica-0
I  master-replica-0 Running local_init_op.  master-replica-0
I  master-replica-0 Done running local_init_op.  master-replica-0
I  master-replica-0 Saving checkpoints for 0 into gs://storxiaohuaeraicom/tensorflowdata/model.ckpt.  master-replica-0
I  master-replica-0 Installing graceful shutdown hook.  master-replica-0
W  master-replica-0 GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.  master-replica-0
I  master-replica-0 Creating heartbeat manager for ['/job:tpu_worker/replica:0/task:0/device:CPU:0', '/job:tpu_worker/replica:0/task:0/device:XLA_CPU:0']  master-replica-0
W  master-replica-0 Worker heartbeats not supported by all workers.  No failure handling will be enabled.  master-replica-0
I  master-replica-0 Init TPU system  master-replica-0
I  master-replica-0 Starting infeed thread controller.  master-replica-0
I  master-replica-0 Starting outfeed thread controller.  master-replica-0
I  master-replica-0 Enqueue next (100) batch(es) of data to infeed.  master-replica-0
I  master-replica-0 Dequeue next (100) batch(es) of data from outfeed.  master-replica-0
W  master-replica-0 

Error occurred during infeed/outfeed.  This may be due to a compile error in the main session.  Waiting for a short time for the main session to come back.

Socket closed  master-replica-0
I  master-replica-0 An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: Socket closed  master-replica-0
E  master-replica-0 Feed error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 434, in _run_infeed
    session.run(self._enqueue_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
UnavailableError: Socket closed
  master-replica-0
E  master-replica-0 Closing session.  A RuntimeError should follow.  master-replica-0
I  master-replica-0 Graph was finalized.  master-replica-0
I  master-replica-0 Restoring parameters from gs://storxiaohuaeraicom/tensorflowdata/model.ckpt-0  master-replica-0
I  master-replica-0 Running local_init_op.  master-replica-0
I  master-replica-0 Done running local_init_op.  master-replica-0
I  master-replica-0 Saving checkpoints for 0 into gs://storxiaohuaeraicom/tensorflowdata/model.ckpt.  master-replica-0
I  master-replica-0 Installing graceful shutdown hook.  master-replica-0
W  master-replica-0 GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.  master-replica-0
I  master-replica-0 Creating heartbeat manager for ['/job:tpu_worker/replica:0/task:0/device:CPU:0', '/job:tpu_worker/replica:0/task:0/device:XLA_CPU:0']  master-replica-0
W  master-replica-0 Worker heartbeats not supported by all workers.  No failure handling will be enabled.  master-replica-0
I  master-replica-0 Init TPU system  master-replica-0
I  master-replica-0 Starting infeed thread controller.  master-replica-0
I  master-replica-0 Starting outfeed thread controller.  master-replica-0
I  master-replica-0 Enqueue next (100) batch(es) of data to infeed.  master-replica-0
I  master-replica-0 Dequeue next (100) batch(es) of data from outfeed.  master-replica-0
--------------------------------------------------------------
my question:
--------------------------------------------------------------
If the ‘ record’ file is small, there is no problem.
so What is the maximum size of “record” ?
or Too many classes？
current num_classes is 27563 and .record file size is 62GB. 
--------------------------------------------------------------
thanks

**Comment by aman2930** [comment]
A TPU node can be used to train 1 model at a time. This error occurs if some model training program have already acquired the TPU and another program is also trying to get the same TPU node. Please check which programs you are running. And run only one at a time on one TPU node.
