### ISSUE TITLE
Can't use preemptible

### ISSUE THREAD

**Issue by prasastoadi** [tensorflow/tpu#195]
When invoking preemptible machine, ctpu gave me non-preemptible flock.

command:
```
ctpu up \
-name=instance-1 \
-zone=us-central1-f \
-tf-version=1.9 \
-preemptible-vm=True \
-preemptible=True \
-machine-type="n1-standard-4"```
```
response:
```
Name:                 instance-1
Zone:                 us-central1-f
GCP Project:          a***
TensorFlow Version:   1.9
VM:
      Machine Type:     n1-standard-4
      Disk Size:        250 GB
      Preemptible:      true
Cloud TPU:
      Size:             v2-8
      Preemptible:      true
```

But the Compute Engine dashboard tells me that the preemptibility is off
![image](https://user-images.githubusercontent.com/11614678/45892717-22011900-bdf3-11e8-9b87-122b42d985d8.png)

Any suggestions?

**Comment by aman2930** [comment]
Its  was a bug which got fixed. It should be available in a week or so. 
Closing this issue for now. Feel free to re-open it if the issue still persist after 2 weeks.
Thanks
