### ISSUE TITLE
num_shards deprecated

### ISSUE THREAD

**Issue by yipsang** [tensorflow/tpu#223]
It can be read from https://www.tensorflow.org/api_docs/python/tf/contrib/tpu/TPUConfig that the `num_shards` of `TPUConfig` has been deprecated, but I can see that most of the official sample models here are still using `num_shards`. Therefore, I would like to ask starting from which version of tensorflow was this attribute deprecated and if I would like to enable model parallelism, what should I do now?

**Comment by saberkun** [comment]
1.12 and 1.13 should work without num_shards and it is auto-derived.
