### ISSUE TITLE
gcloud compute tpus list => ERROR: (gcloud.compute.tpus.list) PERMISSION_DENIED

### ISSUE THREAD

**Issue by alexryan** [tensorflow/tpu#227]
I was trying to debug an error that I am getting when I try to train with MNIST:
`__init__.py:44] file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth`

and was following the troubleshooting steps:
[https://cloud.google.com/tpu/docs/troubleshooting](https://cloud.google.com/tpu/docs/troubleshooting
)

when I got this other strange error:
`>gcloud compute tpus list
ERROR: (gcloud.compute.tpus.list) PERMISSION_DENIED: Read access to project 'annotator-1286' was denied`

I am running running version 1.7 of ctpu on macOS High Sierra

I it unclear to me why I am getting this error.
$GOOGLE_APPLICATION_CREDENTIALS is set correctly.

The active config is also correct.
`>gcloud config list
[compute]
region = us-central1
zone = us-central1-a
[core]
account = annotator@annotator-1286.iam.gserviceaccount.com
disable_usage_reporting = False
project = annotator-1286

Your active configuration is: [annotator]
`

The only thing I can think of is that the zone tpu was launched in a different zone like so.
`ctpu up --zone us-central1-b --preemptible --name alex-tpu`

I'm wondering if this auth issue is related to the auth issue that I am getting when I try to train MNIST on the vm?
[https://cloud.google.com/tpu/docs/tutorials/mnist](https://cloud.google.com/tpu/docs/tutorials/mnist)

**Comment by chrislarkin** [comment]
@alexryan: `gcloud` is using us-central1-a as its default zone. If you created the TPU in another zone, you need to either update the default or pass the zone manually:

`gcloud compute tpus list --zone us-central1-b`
