### ISSUE TITLE
tensorflow v1.12 required but that's unsupported by TPU

### ISSUE THREAD

**Issue by borosdenes** [tensorflow/tpu#228]
Hey! I've ran into two issues while trying to run [resnet_main.py](https://github.com/tensorflow/tpu/blob/master/models/official/resnet/resnet_main.py). I believe both of them are related to tensorflow version mismatch.

First of all the following import only works on tensorflow 1.12 (from tag [v1.12.0-rc0](https://github.com/tensorflow/tensorflow/tree/v1.12.0-rc0/tensorflow/contrib/tpu/python/tpu) to be specific).
https://github.com/tensorflow/tpu/blob/54a6b76ba90822e827117b00df67217cc6a1b22a/models/official/resnet/resnet_main.py#L32
Moreover within `session_config` attribute (see below) of `tf.contrib.tpu.RunConfig` `rewriter_config_pb2.RewriterConfig(disable_meta_optimizer=True)` raises the following error for 1.11 (not under 1.12).
https://github.com/tensorflow/tpu/blob/54a6b76ba90822e827117b00df67217cc6a1b22a/models/official/resnet/resnet_main.py#L521-L534
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Protocol message RewriterConfig has no "disable_meta_optimizer" field.
```

TPU currently only supports tf v1.11, so I do not really know what could be the solution around this. I've tried upgrading tensorflow after starting an a VM with TPU support (started that with `ctpu up`), but that resulted in further bugs, so I assumed that I shouldn't manually update tensorflow after starting an instance with `ctpu up`.

_Update: above mentioned code on **GPU** instance runs, when `--use_tpu=False`, under tf v1.12._

**Comment by saeta** [comment]
Hi @borosdenes !!

Thanks for reaching out. You're absolutely right that the current master branch continues to be developed, and thus currently is incompatible with all available versions of TensorFlow on Cloud TPUs. Fortunately, we create release branches of the [tpu](https://github.com/tensorflow/tpu) (and [models](https://github.com/tensorflow/models) and [main tensorflow](https://github.com/tensorflow/tensorflow)) repositories.

To get going, please use the [r1.11 release branch](https://github.com/tensorflow/tpu/tree/r1.11) for use with the latest Cloud TPUs today. (We're actively working on TF 1.12, but it's not quite ready yet.) If you're using [`ctpu`](https://github.com/tensorflow/tpu/tree/master/tools/ctpu), the right version of all 3 repositories are available on the filesystems of the GCE VM that's created at `/usr/share/{tpu|models|tensorflow}`. Check out the tutorials at [cloud.google.com/tpu/docs](https://cloud.google.com/tpu/docs) (such as [ResNet-50 Image Detection](https://cloud.google.com/tpu/docs/tutorials/resnet#run-model)) which walk you through how to get it done.

If you're taking our reference models and modifying them, you can get the right branch automatically checked out in a single command by executing: `git clone --branch r1.11 https://github.com/tensorflow/tpu`. When we release updated versions, you can either diff between the two branches using `git diff branch_1..branch_2` (or `git diff branch_1...branch_2`) and hand-apply interesting fixes, or alternatively try your luck with a `git rebase`. :-)

Hope that helps!

All the best,
-Brennan

**Comment by borosdenes** [comment]
Hey @saeta !

Thank you very much for your quick and detailed answer. You've answered more than I've asked, all the pieces were very helpful and relevant for my project. Thanks a lot!

Best,
Denes

**Comment by saeta** [comment]
:-) Glad to hear it. Good luck with your project!

**Comment by NielsLindberg** [comment]
shouldn't the tutorial on https://cloud.google.com/tpu/docs/tutorials/resnet default to the branch r1.11 and the vm instance with pip tf 1.11 installed? It took me quite a while to find this post to figure out why the tutorial wasnt working and how to fix it :o.
