### ISSUE TITLE
How to implement tf.image.crop_and_resize with the existing APIs

### ISSUE THREAD

**Issue by hqqxyy** [tensorflow/tpu#230]
Hi,

I find that now only tf.image.central_crop and tf.image.resize_bilinear are supported.  Now they both have some limits, eg, Crop factor must be a compile-time constant. 

tf.image.crop_and_resize is very useful and important for the object detection network. However, it's not supported yet. So can we implement it with the existing APIs?

Thanks,

**Comment by alexander-soare** [comment]
I'll one up this. I know there is a related issue where the suggested solution was to use `tf.tpu.outside_compilation` but depending on the context this can introduce other challenges.

**Comment by hqqxyy** [comment]
Hi, Alexander, Thanks for your reply. It's good to know. TF TPU didn't have the outside compilation API when I opened this issue. This issue is out-dated.
