### ISSUE TITLE
Unable to ssh into ctpu instance

### ISSUE THREAD

**Issue by kulkarnivishal** [tensorflow/tpu#233]
I have a tpu instance running in a google cloud shell and have a model running in a different screen. The problem with the instance is it disconnects after a period of inactivity, i.e., before my code completes its run. It is very very frustrating. So I used ubuntu screen to run the code. Now the code is running but I am unable to ssh into the machine using ctpu after it disconnected. 
It gives: ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].

I am unable to get any work done because of this. Please help. 

Best,
Vishal

**Comment by chrislarkin** [comment]
@kulkarnivishal As long as the vm is healthy you should be able to get back into it. Are you certain that the code isn't hanging? What do you see when you run `ctpu status`?

Have you tried other multiplexers (ie `tmux`), and if so was the behavior the same?

**Comment by chrislarkin** [comment]
@kulkarnivishal I'm going to close this, but feel free to reopen if you're still having issues.
