### ISSUE TITLE
AmoebaNet Export Graph

### ISSUE THREAD

**Issue by JadenLy** [tensorflow/tpu#242]
Hi, I finished training an AmoebaNet. And now I want to freeze the model to get a `.pb` file. However, the `export_model` mode in the code only gives a `.pbtxt` file and some variable files. I wonder if there exists an efficient way to get the `.pb` file. Thanks.

**Comment by ijkilchenko** [comment]
Looking through AmoebaNet, the call to `export_saved_model` has `as_text` set to `True`. Have you tried setting it to `False`?

**Comment by JadenLy** [comment]
@ijkilchenko Thanks for your reply. This modification works and I successfully exported the graph. However, my `.pb` file only has size of 5.17 MB. An `inception v3` model with the same training configuration exceeds 100 MB. So I wonder if there is possible argument I missed to check?

**Comment by WonderAndMaps** [comment]
```
freeze_graph  --input_saved_model_dir=<path_to_export_savedmodel> \
--input_binary=true \
--output_graph=<output_path_to_frozen_amoeba.pb>  \
--output_node_names=predictions
```
should be able to do the job.
