### ISSUE TITLE
output_node_names of AmoebaNet

### ISSUE THREAD

**Issue by zhf526** [tensorflow/tpu#254]
I was trying to freeze the exported graph from the pbtxt file of AmoebaNet. In order to use `freeze_graph`, I need to know the `output_node_names`. I tried to print out the graph summary but it is really messy. Can anyone tell me where to find the output names?

Thanks a lot!

**Comment by WonderAndMaps** [comment]
```
freeze_graph  --input_saved_model_dir=<path_to_export_savedmodel> \
--input_binary=true \
--output_graph=<output_path_to_frozen_amoeba.pb>  \
--output_node_names=predictions
```
should be able to do the job.
