### ISSUE TITLE
Fine Tuning BERT-Base Multilingual model : TPU checkpoints 

### ISSUE THREAD

**Issue by khemon** [tensorflow/tpu#275]
I am trying to fine tune BERT's multilingual pre trained model on a french dataset, using the cloud TPU notebook. However, there is no TPU checkpoint available yet.
I have been experimenting the same using a single GPU, but both tensorflow and pytorch (huggingface repo) takes ages with this infra (~10 sec / batch).  
Could you please tell me if you plan to release TPU checkpoints for the multingual mode ? That would be great  !

**Comment by saberkun** [comment]
The checkpoint should work for TPU?
Latest news is that we have tfhub module for bert which is using TPUEstimator.
https://github.com/google-research/bert/blob/master/README.md
https://tfhub.dev/s?q=bert
