### ISSUE TITLE
MNASNET pre-trained model 

### ISSUE THREAD

**Issue by zychen2016** [tensorflow/tpu#283]
A pre-trained model will be highly appreciated as well.

**Comment by saberkun** [comment]
We have released the saved model and tflite file as you can find inside the mnasnet colab.

**Comment by zychen2016** [comment]
object detection pre-models? @saberkun

**Comment by saberkun** [comment]
We are going to release them in the future along with more object detection works

**Comment by tigert1998** [comment]
How is this model preprocessed? The notebook only resized the sample image. I don't think it's the proper way.
