### ISSUE TITLE
googleapi: Error 403: Read access to project <project-id> was denied, forbidden

### ISSUE THREAD

**Issue by gorkemozkaya** [tensorflow/tpu#284]
Hello,
I'm trying to use the command `ctpu up`, to spin up a tpu flock within the Tensorflow Research Cloud. But whenever I set the default zone to `us-central1-f` using `gcloud config set compute/zone us-central1-f` as per instructions, and then run the `ctpu up` command, I get the message below:
`googleapi: Error 403: Read access to project <project-id> was denied, forbidden`
(The command `ctpu up` works before setting the zone. ctpu version is 1.9)

**Comment by gorkemozkaya** [comment]
Just noticed my TFRC usage period has expired.

**Comment by wmcnally** [comment]
Had same issue when using `ctpu up --tpu-only` to create cloud TPU. Resolved by setting `--zone` flag to where my TFRC credit was allocated.
