### ISSUE TITLE
imagenet_to_gcs.py missing a flag needed to reproduce resnet-50 benchmark

### ISSUE THREAD

**Issue by suchir** [tensorflow/tpu#291]
I'm trying to reproduce the Resnet-50 benchmark used in the DAWNBench competition by following [this tutorial](https://cloud.google.com/tpu/docs/tutorials/resnet-benchmark), but it seems that the script [imagenet_to_gcs.py](https://github.com/tensorflow/tpu/blob/master/tools/datasets/imagenet_to_gcs.py) is missing a flag mentioned in the documentation: `gcs_output_path_small`, used to store a shrunk down version of imagenet.

Without this, it's not possible to do progressive resizing that's presumably needed to reproduce the DAWNBench results. Can this be added? (or, can someone at least specify the behavior of how exactly images are resized down to a smaller version?)

**Comment by ijkilchenko** [comment]
Hi, sorry about that! Our directions on that tutorial got messed, but the solution is to remove the tutorial. If you'd like to reproduce some recent results, take a look at https://github.com/mlperf/training_results_v0.6/tree/master/Google/benchmarks (though I am not familiar with those!)
