### ISSUE TITLE
cloud tpu only works when it's first created with VM instance.

### ISSUE THREAD

**Issue by chenshaolong** [tensorflow/tpu#296]
cloud tpu only works when it's first created with VM instance. When I lost the connection and used ssh to login VM again.  I ran the exactly the same code but it kept giving me the error as follow.

googleapiclient.errors.HttpError: <HttpError 403 when requesting https://tpu.googleapis.com/v1alpha1/projects/directed-sensor-172921/locations/u
s-central1-b/nodes/ai?alt=json returned "Permission 'tpu.nodes.get' denied on 'projects/directed-sensor-172921/locations/us-central1-b/nodes/ai'
">

What should I do to fix this issue? It cost me at least 3 hours to setup all the requirements before running my code. So, I definitely don't want to create new VM instances and TPU nodes every time.
 
Any help would be appreciated in advance!

**Comment by saberkun** [comment]
Added cloud TPU folks @jysohn23 

What's the status of TPU node currently? I don't think TPU node is hooked with VM as a 1-to-1 relationship. If TPU node has some problem, can you try to restart it or create a new one while you can keep the VM.

**Comment by chenshaolong** [comment]
It shows message below after running the command "ctpu st"
No instances currently exist.
	Compute Engine VM:  --
	Cloud TPU:          --

**Comment by saberkun** [comment]
The information is still quite limited. Sorry about that.
You should be able to manage your VM and TPU through GCP console UI. You can start/stop/delete TPU there and choose versions. As the connection is broken and status shows no VM/TPU, probably controlling through UI is more straightforward to see what you till have in the project.

**Comment by chenshaolong** [comment]
Yes. I indeed went through these procedures as well. I just found reconnect is OK. However, the demo code works until I installed some packages for my task. Then, I got the same error as below. But I think I have all the permissions. 

googleapiclient.errors.HttpError: <HttpError 403 when requesting https://tpu.googleapis.com/v1alpha1/projects/directed-sensor-172921/locations/u
s-central1-b/nodes/ai?alt=json returned "Permission 'tpu.nodes.get' denied on 'projects/directed-sensor-172921/locations/us-central1-b/nodes/ai'
">

**Comment by jysohn23** [comment]
Are you authenticated? You could verify this by: `gcloud auth list`
If not try logging in by: `gcloud auth application-default login`

**Comment by chenshaolong** [comment]
Yes, I think so. Here is what I got from runing the command **gcloud auth list**
                  Credentialed Accounts
ACTIVE  ACCOUNT
*       my_account_name

To set the active account, run:
    $ gcloud config set account `ACCOUNT`

**Comment by chenshaolong** [comment]
I think I found the conflict. After I put below information

{
  "type": "service_account",
  "project_id": {project_id},
  "private_key_id": {private_key_id},
  "private_key": {private_key},
  "client_email": {client_email},
  "client_id": {client_id},
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": {client_x509_cert_url}
}

into a file    

    ~/.credentials/service-account.googleapis.com.json 

and then set the env variable to that in .bashrc

   export GOOGLE_APPLICATION_CREDENTIALS=$HOME/.credentials/service-account.googleapis.com.json

and run the command "source .bashrc",  then the conflict occurs.

So, how to fix this issue?

**Comment by Miguel5tuxD** [comment]
> Are you authenticated? You could verify this by: `gcloud auth list`
> If not try logging in by: `gcloud auth application-default login`

This works for me thanks same problem
