### ISSUE TITLE
ShutdownHook: lame workers found

### ISSUE THREAD

**Issue by WonderAndMaps** [tensorflow/tpu#305]
I am constantly seeing  `ShutdownHook: lame workers found: HeartbeatManager(/job:tpu_worker/replica:0/task:0/device:CPU:0)` when I was trying to train AmoebaNet on ml engine on TPU. 

I am not sure whether this is a TPU problem or ml engine problem. Anyone got any ideas or solutions?

![image](https://user-images.githubusercontent.com/40251504/54067103-79077880-41f0-11e9-9591-3776c7c0f66c.png)

**Comment by dapatil211** [comment]
Did you ever figure out what the issue was?

**Comment by WonderAndMaps** [comment]
@dapatil211 Not exactly. But having a smaller `--iterations_per_loop` could be helpful.
