### ISSUE TITLE
amoebanet in code does not match paper!

### ISSUE THREAD

**Issue by MrWanter** [tensorflow/tpu#312]
Hi! It is clearly amoebanet architecture constructed with the code is different from the paper, can someone explain this? same problem also exists with nasnet

specifically, to reproduce the paper's cells in Figure 5, you have to modify the reduction cell from

```
hiddenstate_indices = [1, 0, 0, 2, 1, 0, 4, 0, 1, 0]
used_hiddenstates = [1, 1, 0, 0, 0, 0, 0]
```
to 
```
hiddenstate_indices = [1, 0, 1, 2, 1, 0, 4, 1, 1, 0]
used_hiddenstates = [1, 1, 1, 0, 1, 0, 0]
```
and normal cell from 

```
hiddenstate_indices = [0, 0, 1, 1, 0, 1, 0, 2, 5, 0]
used_hiddenstates = [1, 0, 1, 0, 0, 1, 0]
```
to
```
hiddenstate_indices = [1, 1, 0, 2, 0, 1, 0, 2, 1, 5]
used_hiddenstates = [1, 1, 1, 0, 0, 1, 0]
```

**Comment by bignamehyp** [comment]
It's a drawing mistake. We updated our figure in the latest version of our paper. 
https://arxiv.org/pdf/1802.01548v7.pdf
