### ISSUE TITLE
The cross_replica_batch_normalization implementation seems to be invalid

### ISSUE THREAD

**Issue by santisy** [tensorflow/tpu#321]
Hello all, 
The code for cross_replica_batch_normalization now seems to be invalid. [tpu_normalization.py](https://github.com/tensorflow/tpu/blob/master/models/experimental/mask_rcnn/tpu_normalization.py). 

In the code there, it directly sum up local statistics per core and average that to be the global statistics. For the _mean_, it is fine. But for the variance, it is not correct. 

I think to correctly compute global statistics. What we should do is something like following
```python
# core_num = 8, axis = [0, 1, 2] for using an eight-core tpu and doing
# batch_normalization at 4D tensor whose format is channel last
crp_sum = tf.contrib.tpu.cross_replica_sum
batch_mean = tf.reduce_mean(input_feat, axis=axis, keepdims=True)
mean = crp_sum(batch_mean) / core_num
variance = crp_sum(tf.reduce_mean(tf.square(inputs), axis=axis, keepdims=True)) / \
    core_num - tf.square(mean)
```

**Comment by yeqingli** [comment]
Thanks for the report. We will work on a fix. Stay tuned.

**Comment by saberkun** [comment]
This is fixed. Thx
