### ISSUE TITLE
pytorch versions of models for TPUs?

### ISSUE THREAD

**Issue by denfromufa** [tensorflow/tpu#369]
Last year Google announced support for TPUs in Pytorch. Do you have any reference models yet? Particularly interested in the distributed models presented at Google I/O 2019 for TF/Keras.

https://cloud.google.com/blog/products/ai-machine-learning/introducing-pytorch-across-google-cloud

https://cloud.google.com/blog/products/ai-machine-learning/googles-scalable-supercomputers-for-machine-learning-cloud-tpu-pods-are-now-publicly-available-in-beta

**Comment by jysohn23** [comment]
PyTorch support for TPUs is under active development and you can check out the current progress in the [pytorch/xla](https://github.com/pytorch/xla) repository along with currently working models under test/. We plan to have all future models there too.
