### ISSUE TITLE
EfficientNet drop_connect_rate

### ISSUE THREAD

**Issue by qubvel** [tensorflow/tpu#381]
Am I right that parameter `drop_connect_rate` is never used during training/validation, because all blocks call with default `drop_connect_rate=None` [here](https://github.com/tensorflow/tpu/blob/05f7b15cdf0ae36bac84beb4aef0a09983ce8f66/models/official/efficientnet/efficientnet_model.py#L408)?

**Comment by mingxingtan** [comment]
Hi Pavel, thanks for pointing these out. They all should be trained with drop_connect, but seems like I mistakenly removed them in a unrelated recent change. Let me verify them and get back to you soon.

**Comment by PistonY** [comment]
@mingxingtan Hi, So your paper results are with `drop_connect_rate=None` or this is a bug only in this repo?

**Comment by Callidior** [comment]
Hi @mingxingtan, the paper also mentions a drop-connect rate of 0.3, while the default value in the reference implementation is 0.2. Which one did you actually use?

**Comment by mingxingtan** [comment]
@qubvel bug fixed now, and verified.

@Callidior  Oops, please use drop_connect_ratio=0.2 I will fix the bug in the paper.

**Comment by saberkun** [comment]
We have a commit that fix the missing drop_connect_rate. Thanks
