### ISSUE TITLE
Efficientnet architecture differs from paper

### ISSUE THREAD

**Issue by wagamama** [tensorflow/tpu#383]
https://github.com/tensorflow/tpu/blob/05f7b15cdf0ae36bac84beb4aef0a09983ce8f66/models/official/efficientnet/efficientnet_builder.py#L123

https://github.com/tensorflow/tpu/blob/05f7b15cdf0ae36bac84beb4aef0a09983ce8f66/models/official/efficientnet/efficientnet_builder.py#L124

r3_k3_s22_e6_i40_o80_se0.25 (code) <-> r3_k3_s11_e6_i40_o80_se0.25 (paper)
r3_k5_s11_e6_i80_o112_se0.25 (code) <-> r3_k5_s22_e6_i80_o112_se0.25 (paper)

**Comment by mingxingtan** [comment]
Thanks for pointing this out. The source code is correct. Will update the paper to include the fix soon.
