### ISSUE TITLE
Example on transfer learning usage

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tpu#384]
Hello.

How do I use the pre-trained weights to leverage transfer learning using the different checkpoints provided?

**Comment by ijkilchenko** [comment]
I found an existing [tutorial on transfer learning](https://www.tensorflow.org/alpha/tutorials/images/transfer_learning). It's not TPU specific -- do you have a specific question on how to do this with TPUs?

**Comment by saberkun** [comment]
Hi,

You can use tf.train.init_from_checkpoint (https://www.tensorflow.org/api_docs/python/tf/train/init_from_checkpoint) to use our public checkpoints to do transfer learning. Note that, for TPUEstimator, init_from_checkpoint call should be inside scaffold_fn (https://www.tensorflow.org/api_docs/python/tf/contrib/tpu/TPUEstimatorSpec). 
I will soon provide examples once I fully tested.

**Comment by sayakpaul** [comment]
Hi @ijkilchenko. 

> I found an existing [tutorial on transfer learning](https://www.tensorflow.org/alpha/tutorials/images/transfer_learning). It's not TPU specific -- do you have a specific question on how to do this with TPUs?

I was not asking for a transfer learning tutorial. I am interested in seeing how I can use the EfficientNet models to leverage transfer learning. I hope I am clear now.

**Comment by QuanNguyen94** [comment]
Hi @saberkun, I have tried using the  tf.train.init_from_checkpoint() to load efficientnet-b0 pretrained model as you told, but I have a problem is the assignment_map argument, how can I fit value into this ? Is there anyway beside have to fit all variable name map into ? Thanks

**Comment by jasonchuang** [comment]
Hi @saberkun, cloud you please also provide the similar guide as legacy [flowers](https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/tensorflow/standard/legacy/flowers) example to help us how to implements the image-based **transfer learning** on TPU efficientnet? Thanks

**Comment by see--** [comment]
@saberkun How did you apply the `init_from_checkpoint`? This doesn't work:
```python
  def _scaffold_fn():
    download_path = ('https://storage.googleapis.com/cloud-tpu-checkpoints'
        '/efficientnet/ckptsaug/%s.tar.gz' % FLAGS.model_name)
    ckpt = tf.keras.utils.get_file('pretrained.ckpt', download_path, untar=True)
    tf.logging.info("Restoring from: %s" % ckpt)
    tf.train.init_from_checkpoint(ckpt, restore_vars_dict)
    saver = tf.train.Saver(restore_vars_dict)
    return tf.train.Scaffold(saver=saver)
```
The scaffold function is only applied [during evaluation](https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/main.py#L483-L491).

**Comment by DecentMakeover** [comment]
@QuanNguyen94 Hey can you please share code to load pretrained models, i am not able to load them, opened an issue #497 .Please help

**Comment by sayakpaul** [comment]
I believe a notebook showing the usage of transfer learning with the EfficientNet class of models would be _really_ helpful for the community.

**Comment by SamuelMarks** [comment]
@sayakpaul https://cloud.google.com/tpu/docs/tutorials/efficientnet-2.x

**Comment by SamuelMarks** [comment]
This might prove useful https://cloud.google.com/tpu/docs/tutorials/efficientnet-2.x

**Comment by sayakpaul** [comment]
Thanks for mentioning it. But the [official Keras tutorial on EfficientNet](https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/) is probably the way I would prefer.
