### ISSUE TITLE
efficientnet ran out of memory

### ISSUE THREAD

**Issue by wensdong** [tensorflow/tpu#385]
while following https://cloud.google.com/tpu/docs/tutorials/efficientnet

Status code: Resource exhausted [9x]
  Compilation failure: Ran out of memory in memory space hbm. Used 8.38G of 8.00G hbm. Exceeded hbm capacity by 385.25M.

**Comment by ijkilchenko** [comment]
How did you fix your problem? Usually, when there is not enough memory, you can lower the batch size.

**Comment by wensdong** [comment]
I upgraded to tpu v3
