### ISSUE TITLE
efficientnet training is too slow

### ISSUE THREAD

**Issue by zuokai** [tensorflow/tpu#389]
i use tf1.10, nvidia v100 to train the model efficientnetv0, the params is about 1/4 of my origin model(based on resnet-18), but cost more time(about 10%) than my origin model,
is it normal?

**Comment by saberkun** [comment]
For gpu, should you use 'channels_first'?

**Comment by xrz000** [comment]
Hi @saberkun
I noticed that in [efficientnet_model](https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/efficientnet_model.py), all Conv2D and DepthwiseConv2D use default `data_format='channels_last'`. It should be set to `'channels_first'` for GPU training, right?

**Comment by saberkun** [comment]
Yes, GPU should use channels_first and TPU/CPU should use channels_last. I have not well tested it on GPU. Sorry about that. If you notice any error, please let us know.
@xrz000

**Comment by zuokai** [comment]
@saberkun is the 'channels_first' for all Conv2D and DepthwiseConv2D or just for the DepthwiseConv2D?

**Comment by zuokai** [comment]
@saberkun @xrz000 I changed the dataformat to channels_first and the cost time from 0.87s/batch to 0.67s/batch, still not very fast, my original model is about 4 times larger(parameters) than the efficentnetv0,but it only cost 0.80s/batch with 'channels_last'.

**Comment by saberkun** [comment]
@zuokai 
Everything should be channels_first. 
Are you comparing a model without DepthwiseConv2D? Some ops cost differently on GPU.

**Comment by xrz000** [comment]
@zuokai I have also found training become slower. I was training on my own dataset with InceptionV3 and switched to EfficientnetB2. According to the paper, now I have 1/3 params and 1/6 flops, but speed went from about 2 steps/s to 1.6 steps/s. The inference speed on CPU is faster though.

**Comment by zuokai** [comment]
@saberkun maybe the op DepthwiseConv2D is not efficient on gpu, so is there more efficient way to replace the DepthwiseConv2D on gpu？

**Comment by zuokai** [comment]
@xrz000 https://stackoverflow.com/questions/39368367/tf-nn-depthwise-conv2d-is-too-slow-is-it-normal
which version of the tf are you using？maybe we can try tf1.13

**Comment by xrz000** [comment]
Hi @saberkun 
When I checked the computation graph in tensorboard, I found that all `swish` layers were placed on `CPU:0`, while other parts of model were on GPU. Is this the expected behavior?

**Comment by pidajay** [comment]
@zuokai I am running into very similar issues when training mnasnet and efficient net. When I train with channels first (NCHW) on GPU, it is actually slower than channels last (NHWC) on GPU. Really puzzled since all sources indicate channels first must perform better on GPU. Moreover multi-gpu training does not even work for channels first data format.

**Comment by zuokai** [comment]
@pidajay train with channels first on multi-gpu is much faster（about 30% faster） than channels last(NHWC)

**Comment by liuheng92** [comment]
I have also found this issues, training with efficientnet-b0  is slower than training with resnet50

**Comment by liuheng92** [comment]
> @xrz000 https://stackoverflow.com/questions/39368367/tf-nn-depthwise-conv2d-is-too-slow-is-it-normal
> which version of the tf are you using？maybe we can try tf1.13

I am using tf1.13, it is slow either

**Comment by mrgloom** [comment]
Why `channels_first` is used for GPU training?

**Comment by vidhyasudhanl** [comment]
> Why `channels_first` is used for GPU training?

it improves the load to compute ratio.
