### ISSUE TITLE
The choice of CROP_PADDING

### ISSUE THREAD

**Issue by HaoxuanDou** [tensorflow/tpu#391]
In the preprocessing, `CROP_PADDING` is used to pad the `image_size` to determine a ratio for center crop. Is there a particular reason for the choice of `CROP_PADDING`=32?

**Comment by mingxingtan** [comment]
This is copied from TPU version of ResNet and MnasNet: https://github.com/tensorflow/tpu/blob/222d282c13c205ee0fc1eb960650e0507c627556/models/official/resnet/resnet_preprocessing.py#L23

But I am not sure where it is original from.

**Comment by HaoxuanDou** [comment]
Got it! Thanks
