### ISSUE TITLE
Updated Shakespeare TPU Keras notebook error

### ISSUE THREAD

**Issue by chiayewken** [tensorflow/tpu#398]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): v1.14.0-rc0-66-g648ea74ea0 1.14.0-rc1
- Python version: 3.6.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Running the updated "Predict Shakespeare with Cloud TPUs and Keras" colab notebook, there is an error when calling training_model.fit:

InvalidArgumentError: NodeDef mentions attr 'batch_dims' not in Op<name=GatherV2

**Describe the expected behavior**
training_model.fit starts without error and model is able to train normally.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Running the [official notebook](https://github.com/tensorflow/tpu/blob/master/tools/colab/shakespeare_with_tpu_and_keras.ipynb) in Google Colab with TPU runtime and `!pip install tensorflow==1.14.0rc1`

**Comment by bfontain** [comment]
Hi, !pip install tensorflow==1.14.0rc1 upgrades tensorflow in the Colab but the TPU runtime still uses the offical 1.13 release. Please either wait until 1.14 is released in Colab (i.e. when it is the default install version) or use the [1.13 compatible notebook](https://github.com/tensorflow/tpu/blob/913cf31d85bc31541fbdafa9d0b87db71dd6dcba/tools/colab/shakespeare_with_tpu_and_keras.ipynb) linked from within the official notebook.

I'll keep this issue open until 1.14 is offically available in Colab.

**Comment by bfontain** [comment]
This is fixed as of June 25th with the release of 1.14 on Colab.
