### ISSUE TITLE
RetinaNet: Missing ResNet checkpoint?

### ISSUE THREAD

**Issue by xrayjon3s** [tensorflow/tpu#405]
I'm trying to follow the instructions for training RetinaNet, as described in the README.md file.  I'm having trouble finding the ResNet checkpoint that's mentioned:

"We have provided a pretrained checkpoint using the resnet demonstration model. You can instead train your own resnet model if desired: simply specify a checkpoint from your resnet model directory."

Where is this checkpoint located?  I did find a random ResNet checkpoint (I think from the model zoo) but there were missing layers; seems like it was trained on a different implementation with different layer names.  Thanks!

**Comment by ijkilchenko** [comment]
Read the block of code located just above the sentence you quoted. There is a line that says 

```
RESNET_CHECKPOINT=gs://cloud-tpu-artifacts/resnet/resnet-nhwc-2018-02-07/model.ckpt-112603
```

That's where the checkpoint is located.
