### ISSUE TITLE
Efficient net and mnasnet issue with NCHW data format

### ISSUE THREAD

**Issue by pidajay** [tensorflow/tpu#410]
Looks like the pre-processing steps (mean subtraction and normalization) inherently assume the data format is NHWC. This causes an error when training these models on GPU with NCHW data format. Fixing this lets the training proceed but does not converge.

**Comment by saberkun** [comment]
You can use channel_first for gpu, e.g.: https://github.com/tensorflow/tpu/blob/master/models/official/mnasnet/mnasnet_main.py#L165

**Comment by pidajay** [comment]
But that is precisely the issue! Using channels first data format causes the script to fail because of a number of reasons
1. The pre-processing steps assumes the data will always be channels last (even after the data format is set to channels first).
2. There are also several layers in the model (both efficient net and mnasnet) that don't accept the data format (and hence assumes channels last). For eg. Conv2D.
After fixing 1 and 2 I can get the model to run but it doesn't converge the same way as the TPU model.

**Comment by vidhyasudhanl** [comment]
Is this issue still open? Efficientnet on GPU with  --data_format=channels_first --transpose_input=false results in      ValueError: Dimensions must be equal, but are 16 and 32 for 'efficientnet-b0/model/blocks_0/Add_1' (op: 'Add') with input shapes: [32,16,112,112], [32,32,112,112].

**Comment by bnascimento** [comment]
> Is this issue still open? Efficientnet on GPU with --data_format=channels_first --transpose_input=false results in ValueError: Dimensions must be equal, but are 16 and 32 for 'efficientnet-b0/model/blocks_0/Add_1' (op: 'Add') with input shapes: [32,16,112,112], [32,32,112,112].

just bumped into the same problem. any news?
