### ISSUE TITLE
TPU with official PyTorch support!

### ISSUE THREAD

**Issue by CyFeng16** [tensorflow/tpu#415]
> https://github.com/tensorflow/tfrc/issues/2#issue-459195889

#369 

Eager to know the current supported version of PyTorch!
[tpu-pytorch.png](https://drive.google.com/file/d/1QHfL7tLNfyZ7JG2-iqgBpWF3pU_5fDDC/view?usp=sharing)

Any news and discussion are welcome.

**Comment by jysohn23** [comment]
Hi,

You can track progress on the [pytorch/xla](https://github.com/pytorch/xla) where there should also be instructions on `How to Run PyTorch with TPUs`. We'll track all future progress there. Thanks.

**Comment by CyFeng16** [comment]
@jysohn23 Thanks!
So, the implementation is referenced from [pytorch/xla](https://github.com/pytorch/xla), not google cloud's own implementation. 
Is that right?

**Comment by jysohn23** [comment]
Not sure what you mean by Google Cloud's own implementation, but [pytorch/xla](https://github.com/pytorch/xla) is where we'll have most models TPU compatible implementation (in the short term at least). Lot's of PyTorch models should require very minimal bootstrapping change to be TPU compatible.

**Comment by CyFeng16** [comment]
Many thanks.
