### ISSUE TITLE
Efficientnet Layer naming

### ISSUE THREAD

**Issue by bintonto** [tensorflow/tpu#428]
Why do all layer names have to be followed by a down line?
e.g. self._dropout, self._fc, self._avg_pooling

**Comment by ijkilchenko** [comment]
This is more a Python convention. It's like saying that anything prefixed by `_` is meant to be thought of as private (or at least you wouldn't want to be reusing that variable outside of a class or something like that).

**Comment by saberkun** [comment]
It is google python style guide.
These inner layers should not be public accessible.
