### ISSUE TITLE
Can we train efficient net on gpu??

### ISSUE THREAD

**Issue by QuickLearner171998** [tensorflow/tpu#432]
Does efficient net use mix point precision? If yes can I train it on GPU and use it as a backbone architecture for mask rcnn?

**Comment by saberkun** [comment]
Yes. use_tpu=false will get to use gpu if gpu is available. 
Yes, we exposed endpoints tensors for feature extraction and are experimenting with maskrcnn. We did not released the configuration yet because we want to make sure things are promising. Thanks

**Comment by heartInsert** [comment]
Thanks

**Comment by RituYadav92** [comment]
@QuickLearner171998 
Were you able to use efficient net as backbone of maskrcnn ??
