### ISSUE TITLE
Is there any tensorflow install option for TPU

### ISSUE THREAD

**Issue by panfeng-hover** [tensorflow/tpu#444]
The option for CPU and GPU ones are:

`pip install tensorflow` or `pip install tensorflow-gpu`

I am wondering whether similar `pip install tensorflow-tpu` available, it seems that I could only use the TPU tensorflow version by `ctpu up`, and it would be better if I can install it in conda envs.

**Comment by ijkilchenko** [comment]
No, there is no TPU version.
