### ISSUE TITLE
How can I train mnasnet using CPU or GPU on GCP 

### ISSUE THREAD

**Issue by mylovekj** [tensorflow/tpu#445]
I have used GCP VM to run mnasnet using CPU.

I set the parameter "--use_tpu=false" but result message is "RuntimeError: You need to specify a TPU Name if you are running in the Google Cloud environment."

Is there any other way to run mnasnet on GCP not use TPU?

![image](https://user-images.githubusercontent.com/52939349/61254774-c00a0980-a7a0-11e9-99b6-cc43d16e61d3.png)

**Comment by saberkun** [comment]
Thank you for reporting. This is clear a bug introduced in a recent refactoring. 
Will update with a fix soon.

**Comment by saberkun** [comment]
I think setting tpu_cluster_resolver to None will fix your issue.
I had commit: https://github.com/tensorflow/tpu/commit/83b7420c8fe261eb55359caa7fab8f9c02b81706

let us know if it is fixed.

**Comment by mylovekj** [comment]
Thank you. It work.

**Comment by mylovekj** [comment]
But I have one more question.
Can I specify tensorflow worker parameter?
