### ISSUE TITLE
The import path issue still exists in mask_rcnn_main.py

### ISSUE THREAD

**Issue by panfeng-hover** [tensorflow/tpu#454]
Inside the mask_rcnn_main.py,

```
import dataloader
import distributed_executer
import mask_rcnn_model
from configs import mask_rcnn_config
```

Currently if `import sys; print(sys.path)` before the line `from configs import mask_rcnn_config`, the `sys.path` is

```
['tpu/models/official/efficientnet', 'tpu/models/official/mnasnet', '/home/panfeng/projects/tpu/models/official/mask_rcnn', '/home/panfeng/projects/tpu/models', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/panfeng/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
```

So Python would first look as `configs/` under `tpu/models/official/mnasnet`, which will cause error:

```
Traceback (most recent call last):
  File "tpu/models/official/mask_rcnn/mask_rcnn_main.py", line 31, in <module>
    from configs import mask_rcnn_config
ImportError: cannot import name mask_rcnn_config
```

This issue starts to exist since `r1.14`, and also in the `master` branch, which is due to there is no `configs/` folder under `mnasnet` in `r1.13`.

Simply re-insert the path,
```
import sys; sys.path.insert(0, 'tpu/models/official/mask_rcnn')
from configs import mask_rcnn_config
```
could solve it.

By the way, this issue also exists in the `export_saved_model.py` under `mask_rcnn`.

To verify this issue, set a breakpoint before `from configs import mask_rcnn_config` and 
```
(Pdb) import configs
(Pdb) configs
<module 'configs' from 'tpu/models/official/mnasnet/configs/__init__.py'>
```

**Comment by allenwang28** [comment]
Hi,
Thanks for bringing this up. We've repro'd and fixed this by appending MNasNet path instead (https://github.com/tensorflow/tpu/commit/c10899a014d82d2eba4d373bde416c16a142be3c for r1.14 and https://github.com/tensorflow/tpu/commit/ae3cbb1d882a66b25711b58ea9b21bc51207d82b for nightly)
