### ISSUE TITLE
efficientnet-edgetpu: inconsistent model name in checkpoint 

### ISSUE THREAD

**Issue by skyflynil** [tensorflow/tpu#460]
Thank you for providing the efficientnet-edgetpu and checkpoints. 
There is some inconsistency between the model name for the code and corresponding checkpoint file though.
code: efficientnet-edgetpu-X
checkpoint: edgetpunet-X

restore model from checkpoint will throw variable not found error.
Manually change model name to edgetpunet-X in eval_ckpt_main.py and efficientnet_edgetpu_builder.py worked.

**Comment by saberkun** [comment]
Thanks for reporting! Fixing

**Comment by saberkun** [comment]
Should be fixed. Printed variables. they are now: efficientnet-edgetpu-S/blocks_0/conv2d/kernel, etc.
