### ISSUE TITLE
'Learn Data Augmentation for Object Detection' doesn't work at all

### ISSUE THREAD

**Issue by poodarchu** [tensorflow/tpu#461]
autoaugment_utils.py has several bugs, so how did you achieve mAP reported in the paper?

More details can be found here: https://github.com/poodarchu/learn_aug_for_object_detection.numpy

**Comment by sefira** [comment]
https://github.com/tensorflow/tpu/blob/master/models/official/detection/utils/autoaugment_utils.py#L686

I think I've found another bug for Learning Data Augmentation Strategies for Object Detection seen above link, in which an image is augmented as many time as the number of bboxes in it.
Assuming we are augmenting the bboxes and images by random flipping, in this case, each bbox is flipped by a probability P, but the image will be flip many times and the probability is not equal to P.

**Comment by TccccD** [comment]
@poodarchu , Recently, I am also using this enhanced search strategy to enhance the data of the detection task. I also found that it is worse than the non-enhancement effect. I want to ask if you found the mAP lower under the tensor version, and you. Why have you closed this question?
