### ISSUE TITLE
Efficient Net on Edge TPU accuracy lower than documented

### ISSUE THREAD

**Issue by wuhy08** [tensorflow/tpu#483]
Hi,
I am benchmarking EfficientNet with EdgeTPU (Coral). The inference time on Coral is similar to what's published. However, the ImageNet Top-1 accuracy is much lower than what's in the document. Below is my result:

Model | Top-1 accuracy (%) | Top-5 accuracy (%)
------------ | -------------|------------------------
EffNet-EdgeTPU-S | 48.5  | 70.6
EffNet-EdgeTPU-M  |  60.0                   |             81.2
EffNet-EdgeTPU-L         |       56.2              |                  77.4

The model I used is directly downloaded from Coral Website (https://coral.withgoogle.com/models/).
The label map file I used is from https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/eval_data/labels_map.txt

The code snippet for classification inference is the following:
```   
engine = ClassificationEngine(model_file_name)
for img_file in img_files:
    img = Image.open(img_file)
    results_raw = engine.ClassifyWithImage(img, top_k=5, threshold=1e-7)
    results = [r[0] for r in results_raw]
```

Is this due to quantization? I also used edgetpu_compiler to convert raw model to edgetpu, which gives me similar result. I didn't test the raw model.

**Comment by saberkun** [comment]
What's your preprocessing code?
We measured the accuracy and then reported. 
There might be some discrepancy.

**Comment by saberkun** [comment]
Please use the code here to match preprocessing: https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/export_model.py#L78

**Comment by wuhy08** [comment]
Hi @saberkun 
Thank you for the reply. I am using Coral's classification Engine, therefore their default transform. From the source code, it seems that the image is resized (aspect ratio not preserved) and convert to numpy.array.   (https://coral.googlesource.com/edgetpu/+/refs/heads/release-chef/edgetpu/classification/engine.py#45)

Let me read your source code and investigate a little.

Thank you

**Comment by volcacius** [comment]
Hello, 

@wuhy08 I'm experiencing the same issue you reported here. I was wondering if you had looking getting the reported accuracy using the model distributed on the Coral website. Changing to crop+resize to just resize doesn't seem to make much difference.

Thanks

**Comment by wuhy08** [comment]
HI @volcacius ,

I put this work aside and haven't looked at it since then. Sorry I couldn't help more. I might continue to investigate it if I have more time.
