### ISSUE TITLE
EfficientNet not performing well when training is set to False

### ISSUE THREAD

**Issue by IdoWSC** [tensorflow/tpu#491]
Hi,
I am using efficientnet_builder.build_model (training arg set to True) in order to train efficientnet-b5 with a training script I wrote and use tf.train.Saver() to save the trained model.

When i try to use this checkpoint for inference i use  efficientnet_builder.build_model with training arg set to False and load the model using tf.train.Saver() I get really bad results that don't resemble the training session in anyway. However when I set training arg to True the net performs correctly and the results are correlated to the results in the training session.

I also tried to save the ckpt during training with tf.train.Saver(tf.global_variables()) to save moving averages variables with no success.

Does anyone have an idea whats the source of the difference?

Thanks!

**Comment by IdoWSC** [comment]
I think I understood the source for the issue. 
I think the problem occurred since I initiate the update ops every step:
`
update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
with tf.control_dependencies(update_ops):
    optimizer = optimizer.minimize(cost, global_step=global_step)
`
However, now that I added this part to the training, I can't run a training step due to GPU memory overflow.
Here is the traceback:
`
019-09-07 21:32:46.702270: W tensorflow/core/common_runtime/bfc_allocator.cc:271] ****************************************************************************************************
2019-09-07 21:32:46.702314: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at transpose_op.cc:199 : Resource exhausted: OOM when allocating tensor with shape[10,12,12,2688] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/home/wscuser/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/wscuser/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/wscuser/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[10,12,12,2688] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node efficientnet-b4/model/blocks_31/tpu_batch_normalization/batchnorm/add_1-0-0-TransposeNCHWToNHWC-LayoutOptimizer}}]]
`

I'm trying to train efficientnetb4 with a V100 GPU, with batch size of 10.

Does anyone know if this is normal?

**Comment by mingxingtan** [comment]
Looking at this log, seems like the NCHWToNHWC transpose takes a lot of memory. Could you try to change the input format?

The default format is good for TPU, but may not be the best for GPU, so better to try both formats NCHW and NHWC.

**Comment by IdoWSC** [comment]
Thanks for the input @mingxingtan.
Can you give me a clue where can I change the input format?

**Comment by saberkun** [comment]
Yes, for GPU, please use regular batch norm.
