### ISSUE TITLE
Not able to load pretrained models using TPU

### ISSUE THREAD

**Issue by DecentMakeover** [tensorflow/tpu#497]
I am trying to load pretrained EffecientNet weights and i was getting this error

	InvalidArgumentError: Cannot assign a device for operation stem_conv/kernel/IsInitialized/VarIsInitializedOp: node stem_conv/kernel/IsInitialized/VarIsInitializedOp (defined at /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:422) was explicitly assigned to /job:worker/replica:0/task:0/device:TPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device.
			 [[stem_conv/kernel/IsInitialized/VarIsInitializedOp]]

But even when i try to load resnext50 i get the same issue Any suggestions?

	InvalidArgumentError: Cannot assign a device for operation stem_conv/kernel/IsInitialized/VarIsInitializedOp: node stem_conv/kernel/IsInitialized/VarIsInitializedOp (defined at /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:422) was explicitly assigned to /job:worker/replica:0/task:0/device:TPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0 ]. Make sure the device specification refers to a valid device.
			 [[stem_conv/kernel/IsInitialized/VarIsInitializedOp]]

**Comment by saberkun** [comment]
Hi, How do you load checkpoints?

With TPUEstimator, only using scaffold_fn can do this correctly.
See example here: https://github.com/tensorflow/tpu/blob/master/models/official/mnasnet/mnasnet_main.py#L549
