### ISSUE TITLE
Could you please explain the reason why there is an ema here?

### ISSUE THREAD

**Issue by CoinCheung** [tensorflow/tpu#501]
Hi, 

I am reading the code of efficientnet, and I noticed this line: 

https://github.com/tensorflow/tpu/blob/7deb5c03e01d4af89a9f7994f03f4fcad58eaed4/models/official/efficientnet/main.py#L365

I am not quite familiar with tensorflow, would you please tell me what this ema is doing ? Does it implement ema on the model parameters updates every training step like what lookahead optimizer does?

**Comment by saberkun** [comment]
https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage

EMA in principle is taking average with previous variable values in previous checkpoints.
See explanations in http://ruishu.io/2017/11/22/ema/

It is a common training trick.

**Comment by glenn-jocher** [comment]
@saberkun is the ema shadow model updated every batch or every epoch? If the decay is 0.999 I'm assuming it must be updated extremely often, thus I'm assuming it must be updated every batch or every optimizer update?

**Comment by mingxingtan** [comment]
It is updated every batch.
