### ISSUE TITLE
MnasNet example - Wrong label mapping

### ISSUE THREAD

**Issue by nsarang** [tensorflow/tpu#521]
The MnasNet model predicts probabilities for 1000 classes, however, the provided imagenet module has 1001 classes, with "background" being a dummy class. Hence, label indices should be incremented by one.
https://github.com/tensorflow/tpu/pull/507

**Comment by saberkun** [comment]
When we train it, in the input pipeline, there is a "minus 1".

**Comment by nsarang** [comment]
I agree that the model was trained correctly. I was just pointing to the wrong interpretation of the model's output in the [example notebook](https://github.com/tensorflow/tpu/blob/master/models/official/mnasnet/mnasnet_example.ipynb). Label indices should be incremented by one. Please have a look at https://github.com/tensorflow/tpu/pull/507

**Comment by mingxingtan** [comment]
Thanks Nima! It was my mistake. I have approved and merged your pull request.
