### ISSUE TITLE
Official efficientnet broken for all non-1000 class datasets  ( --num_label_classes ignored)

### ISSUE THREAD

**Issue by UsmannK** [tensorflow/tpu#540]
The --num_label_classes option in main.py on master is now ignored in https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/imagenet_input.py#L85, breaking any training that is not being done on 1000 or 1001 classes.. This worked fine in r1.14.

Related: I don't think https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/main.py#L606 is a great idea. It assumes imagenet, which is probably only going to be the case when running benchmarks. Could this be moved into its own flag?

**Comment by CyFeng16** [comment]
Hi Usmann,
As far as I understand, the 1000 classification setting only applies to the use of tpu to reproduce the efficientnet paper. If it is another application scenario, for the following two examples:

- According to the efficientnet modification to get a new model for research, ImageNet will still be the standard test data set (1000 classification stands).
- Using efficientnet to extract features for migration learning, it is a good choice to simply use efficientnet as a feature extractor. The number of classifications is up to you (simply write two lines of code after it). > https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet#3-using-efficientnet-as-feature-extractor

Of course, a generic flag and feature-compatible code is a definitely good choice, which is exactly 
 I did as I trained the case-sensitive data set from scratch.

**Comment by UsmannK** [comment]
@CyFeng16 I think you may have missed my point. The generic flag for num_classes is already in the codebase. It worked in previous versions and has regressed since. It is no longer functional.

**Comment by CyFeng16** [comment]
@UsmannK Now I get you. Although I have not actually tried it, the parameters appear to still take effect depending on the [code](https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/efficientnet_builder.py#L247).

**Comment by mingxingtan** [comment]
@CyFeng16  You are right, the recent CL breaks this code. I am fixing it now. Thanks for pointing this out.

**Comment by CyFeng16** [comment]
@mingxingtan  GJ! And also look forward to TF2.1, which has full TPU support(v2.0).

**Comment by mingxingtan** [comment]
@UsmannK fix is submitted. It is on the way to github.

**Comment by UsmannK** [comment]
Thank you @mingxingtan!

**Comment by UsmannK** [comment]
> @UsmannK Now I get you. Although I have not actually tried it, the parameters appear to still take effect depending on this [code](https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/main.py#L316) and this [code](https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/efficientnet_builder.py#L247).

I think there has been a commit since my original message, for posterity's sake the line I meant to point out was: https://github.com/tensorflow/tpu/blob/16ccb8ae810c6afc3348b00a0b7d5be80b0fb085/models/official/efficientnet/imagenet_input.py#L95

**Comment by CyFeng16** [comment]
@UsmannK #557 ::tada::
