### ISSUE TITLE
Training tf.keras models (TensorFlow 2.0) using Cloud TPUs

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tpu#572]
Hi. Referring to [this tutorial](https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/fashion_mnist.ipynb#scrollTo=N6ZDpd9XzFeN) I was wondering if we could do the same with TensorFlow 2.0. If yes, what would be the required changes?

**Comment by saberkun** [comment]
Please check out models inside https://github.com/tensorflow/models/tree/master/official
Note that TF 2.0 only has experimental support. It is better to use tf-nightly
