### ISSUE TITLE
Support for tf.where without x and y arguments

### ISSUE THREAD

**Issue by aidangomez** [tensorflow/tpu#584]
I have an application that desperately requires I construct a list of the indices where a boolean takes on a True value.

Below is an implementation for tpu that I've been iterating on but unfortunately it fails due to the while loop having non-static shape invariants. TPUs don't support dynamic size TensorArrays so those aren't an option it appears.

Would anyone on the TPU team have a strategy to implement something like this given existing ops / would someone be willing to implement the OP in XLA?

```python3
def tpu_where(boolean_tensor):
  shape = shape_list(boolean_tensor)
  ta = tf.TensorArray(dtype=boolean_tensor.dtype,
                      size=np.prod(shape),
                      clear_after_read=True,
                      dynamic_size=False)
  ta = ta.unstack(tf.reshape(boolean_tensor, [-1]))

  def cond(_, *i):
    return tf.reduce_all([j < shape[idx] for idx, j in enumerate(i)])

  def body(t, *i):
    bt = 0
    multiplier = 1
    for idx, j in reversed(list(enumerate(i))):
      bt += j * multiplier
      if idx > 0:
        multiplier *= shape[idx]
    bt = ta.read(bt)
    t = tf.cond(bt, lambda: tf.concat([t, [[*i]]], axis=0), lambda: t)

    carry = 1
    idx_list = []
    for idx, j in reversed(list(enumerate(i))):
      j += carry
      carry = tf.math.floordiv(j, shape[idx])
      if idx > 0:
        j = tf.math.mod(j, shape[idx])
      idx_list.append(j)

    return (t, *idx_list)

  loop_vars = [tf.zeros(dtype=tf.int32, shape=[1, len(shape)])]
  loop_vars += [tf.constant(0) for _ in range(len(shape))]

  outputs, *_ = tf.while_loop(
      cond,
      body,
      loop_vars,
      shape_invariants=[tf.TensorShape([None, len(shape)])] +
      [tf.TensorShape(()) for _ in range(len(shape))],
      parallel_iterations=1,
      maximum_iterations=None,
      return_same_structure=False)

  return outputs
```

**Comment by blakehechtman** [comment]
dynamic sized  tf.where with a single argument should work now

**Comment by yunxing** [comment]
We only added the support a week ago, could you try tf nightly and let us know if it works?

**Comment by aidangomez** [comment]
Oh brilliant, thank you both so much. I’ll report back here and close the
issue of it works.

**Comment by aidangomez** [comment]
FYI Working on this now; it will take me some time to refactor my code to support TF 2.0 but I will update this issue with results once I have them.

**Comment by aidangomez** [comment]
This works on the latest TF 2 nightly; thanks for your help. FYI, I can't use any tf.metrics as they seem to cause segfaults when I call update_state(...) or result().

**Comment by yunxing** [comment]
No problem. Just for clarification, is the segfault a separate bug?
