### ISSUE TITLE
Error on TPU Pod 

### ISSUE THREAD

**Issue by rd16395p** [tensorflow/tpu#596]
I am trying to connect to my TPU Pod using the documentation found here and the example in the TPU github for MNIST.

https://cloud.google.com/tpu/docs/training-on-tpu-pods

However, when I try to connect, I receive the following error;
[I1107 14:24:47.276069 140521844594496 transport.py:157] Attempting refresh to obtain initial access_token
[W1107 14:24:47.301813 140521844594496 http.py:118] Invalid JSON content from response: b'{\n "error": {\n "code": 403,\n "message": "Request had insufficient authentication scopes.",\n "status": "PERMISSION_DENIED"\n }\n}\n'

Does anyone know how to fix this issue? I have ran gcloud init to ensure I am using my account.

**Comment by CyFeng16** [comment]
It is that your GCE instance does not have the right to access TPU domain. 
Just Check the GCE instance's configuration and give it all necessary access right needed.

**Comment by CyFeng16** [comment]
@rd16395p You may want to read [this](https://cloud.google.com/compute/docs/access/service-accounts?_ga=2.70176020.-544486021.1571903860).

**Comment by rd16395p** [comment]
Yes that was the issue, I changed it via editing the VM. Cheers!

**Comment by CyFeng16** [comment]
@rd16395p Congrats and enjoy the TPUs.

**Comment by manhlab** [comment]
please tell me how you fixed this. I tried it but not success !

**Comment by rd16395p** [comment]
> 
> 
> please tell me how you fixed this. I tried it but not success !

You need to edit the VM to have permissions to do the task.

**Comment by manhlab** [comment]
sorry but I already have this 
![Screenshot_20200614_142531](https://user-images.githubusercontent.com/47383746/84592009-38fb6080-ae4b-11ea-8a94-ccc3cf9c6987.png)

**Comment by manhlab** [comment]
I try to create a new key. But I think all think is already but don't know Why not running TPU?

**Comment by rd16395p** [comment]
@manhlab Did you try fixing the VM? 

Do you have a TPU instance running?

**Comment by manhlab** [comment]
what i did: run VM, run TPU 
export TPU_NAME=****

**Comment by rd16395p** [comment]
@manhlab 
1. Create a VM with those settings I link to
2. Create a TPU and get the IP to connect to. You can find this in the details of it. 
3. Use the following code ; and follow along to " Get TPU Address"; 
https://blog.tensorflow.org/2019/01/keras-on-tpus-in-colab.html

**Comment by manhlab** [comment]
thanks for your advince. but i am running code on colab. all working with my code. but don't know how to link TPU GC and VM instance. This is first time of me

**Comment by manhlab** [comment]
i still cant fix this. please help me

**Comment by rd16395p** [comment]
@manhlab Show me your connection string and I can help you edit it.

**Comment by rd16395p** [comment]
@manhlab https://github.com/rd16395p/TPU-Pod-Examples/tree/master/iris%20example
This code may help you. I have instructions on how to use it as well.
