### ISSUE TITLE
The base_url in imagenet_to_gcs.py can no longer download file from ImageNet

### ISSUE THREAD

**Issue by RuiLiFeng** [tensorflow/tpu#604]
Directly run the imagenet_to_gcs.py will cause tarFile OSError
![image](https://user-images.githubusercontent.com/33709183/69006776-0c43a100-096f-11ea-976c-052b2680f2bd.png)
After looking into the source code I found the base_url :
http://www.image-net.org/challenges/LSVRC/2012/nnoupb/
is now invalid in imagenet website and can no longer download images.
![image](https://user-images.githubusercontent.com/33709183/69006800-6ba1b100-096f-11ea-8047-56126bd6d19b.png)
I change the base_url manually into the correct one then every thing works.

By the way, the imagenet_username and imagenet_accsess_key are not used at all! Why bother to set these two args? Also, the imagenet_access_key refers to a long string generated by the Imagenet Website, which could be found in the  account profile, while the tpu turioal 
https://cloud.google.com/tpu/docs/imagenet-setup
refer it as the password to the username, which is quite confusing (but this dont cause error because the scripts doesnt use them at all)
![image](https://user-images.githubusercontent.com/33709183/69006804-8aa04300-096f-11ea-9ad0-17b42bba5959.png)
![image](https://user-images.githubusercontent.com/33709183/69006817-c5a27680-096f-11ea-94bb-a47a07a34fe2.png)

**Comment by wohlbier** [comment]
What is the correct base_url?

**Comment by yisitu** [comment]
The path is not supported I believe.

You'll need to manually download the tar files from:
http://image-net.org/challenges/LSVRC/2012/downloads

Then, follow section "Image-Net with existing .tar files from Image-Net" from https://github.com/tensorflow/tpu/tree/master/tools/datasets#imagenet_to_gcspy

**Comment by snehilverma41** [comment]
To make use of the existing script:
1. Given that you have access to download images from [ImageNet](http://www.image-net.org), go to [http://www.image-net.org/challenges/LSVRC/2012/downloads](http://www.image-net.org/challenges/LSVRC/2012/downloads).
2. Copy link address of any of the zip files from the page.
3. Let's say the link is `http://www.image-net.org/challenges/LSVRC/2012/<UNIQUE_ID>/ILSVRC2012_img_train.tar`, copy your `<UNIQUE_ID>` and replace it with `nnoupb` on line78 of `imagenet_to_gcs.py`.

The script should now work.

Note that according to the Terms of use of ImageNet, it is NOT allowed to distribute the URLs.

**Comment by allenwang28** [comment]
Thank you for creating this issue, @yisitu and @snehilverma41 are correct in that the download path is not supported any longer. I've updated the script to reflect this.
