### ISSUE TITLE
AutoAugment translateX(Y) questions

### ISSUE THREAD

**Issue by caterpillars** [tensorflow/tpu#627]
I am trying AutoAugment. When using test policy: 
policy = [[('TranslateX_BBox', 1.0, 4)], ]
the actual shifted pixels are random flipped (i.e. sometimes translated by -100 pixel, sometimes translated by +100 pixel). This is because the level are flipped with 50% of the chance. But the bbox translation very often are not consistent with the image translation. I tried running the same code 7 times with the policy above. Here are the results:
        image_translated      bbox_translated
1 .             100                         100
2.              100                         100
3.              100                         100
4.               -100                      100
5.               -100                      100
6               -100                       100
7              100                          -100

My questions are:
1) 'pixel' for bbox and translate_x are all from function call translate_bbox. Why the shifted results are different? 
2) Is this intended behavior?

Thanks

**Comment by BarretZoph** [comment]
Hi I do not see this issue when running the code on my end. How are you viewing the pixel value for bbox and translate_x? Are you running a .eval() method on them or fetching them from the TF graph?

**Comment by caterpillars** [comment]
I am running eval on them, I think that explains the behavior.
