### ISSUE TITLE
AttributeError when running create_coco_tf_record.py

### ISSUE THREAD

**Issue by qiningonline** [tensorflow/tpu#639]
Due to the recent change of the following line

https://github.com/tensorflow/tpu/blob/e68d0229285b40e001da9ac0d62b969f303b058d/tools/datasets/create_coco_tf_record.py#L46

Running create_coco_tf_record.py leads to an `AttributeError`

Changing this line back to `import tensorflow as tf` fixed the issue of inconsistency

https://github.com/tensorflow/tpu/blob/e68d0229285b40e001da9ac0d62b969f303b058d/tools/datasets/create_coco_tf_record.py#L113

```
Traceback (most recent call last):
  File "create_coco_tf_record.py", line 372, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "create_coco_tf_record.py", line 358, in main
    if not tf.compat.v1.gfile.IsDirectory(directory):
AttributeError: 'module' object has no attribute 'v1'
```

**Comment by allenwang28** [comment]
Thanks for bringing this up. This should be fixed with https://github.com/tensorflow/tpu/pull/647/commits/19479c5839d99e798331af2607dec84851da4e3f
