### ISSUE TITLE
Official demo code RetinaNet TPU training failed Error recorded from infeed: From /job:worker/replica:0/task:0:

### ISSUE THREAD

**Issue by bittnt** [tensorflow/tpu#644]
I am using Google Cloud, and happen to run the demo code retinanet TPU following the l[TPU Retinannet tutorial](https://cloud.google.com/tpu/docs/tutorials/retinanet). After running the following line:
```
python /usr/share/tpu/models/official/detection/main.py \
     --use_tpu=True \
     --tpu=${TPU_NAME:?} \
     --num_cores=8 \
     --model_dir="${MODEL_DIR?}" \
     --mode="train" \
     --eval_after_training=True \
     --params_override="{ type: retinanet, train: { checkpoint: { path: ${RESNET_CHECKPOINT?}, prefix: resnet50/ }, train_file_pattern: ${TRAIN_FILE_PATTERN?} }, eval: { val_json_file: ${VAL_JSON_FILE?}, eval_file_pattern: ${EVAL_FILE_PATTERN?}, eval_samples: 5000 } }"
```
 The error message is shown as follows
```
I1227 05:12:02.113799 139709221000640 tpu_estimator.py:576] Initialized TPU in 8 seconds
INFO:tensorflow:Starting infeed thread controller.
I1227 05:12:02.114499 139707043796736 tpu_estimator.py:521] Starting infeed thread controller.
INFO:tensorflow:Starting outfeed thread controller.
I1227 05:12:02.114758 139707072362240 tpu_estimator.py:540] Starting outfeed thread controller.
I1227 05:12:02.163481 139707080754944 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpu-retinanet-1 in state READY, and health HEALTHY.
W1227 05:12:02.226492 139707080754944 preempted_hook.py:91] TPUPollingThread found TPU tpu-retinanet-1 in state READY, and health HEALTHY.
INFO:tensorflow:Enqueue next (100) batch(es) of data to infeed.
I1227 05:12:02.803231 139709221000640 tpu_estimator.py:600] Enqueue next (100) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (100) batch(es) of data from outfeed.
I1227 05:12:02.803647 139709221000640 tpu_estimator.py:604] Dequeue next (100) batch(es) of data from outfeed.
ERROR:tensorflow:Error recorded from infeed: From /job:worker/replica:0/task:0:
{{function_node __inference_tf_data_experimental_map_and_batch_<class 'dataloader.retinanet_parser.Parser'>_3083}} indices[0] = 0 is not in [0, 0)
         [[{{node parser/GatherV2}}]]
         [[input_pipeline_task0/while/IteratorGetNext]]
I1227 05:12:25.146676 139707052189440 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpu-retinanet-1 in state READY, and health HEALTHY.
W1227 05:12:25.230767 139707052189440 preempted_hook.py:91] TPUPollingThread found TPU tpu-retinanet-1 in state READY, and health HEALTHY.
I1227 05:12:32.299117 139707080754944 transport.py:157] Attempting refresh to obtain initial access_token
WARNING:tensorflow:TPUPollingThread found TPU tpu-retinanet-1 in state READY, and health HEALTHY.
```
I think it might due to that the TPU is not healthy, and I recreate v3-8 TPU again and again, it repeated the same error message.  Interestingly, I have tried out based on the TensorFlow Object Detection API TPU demo, everything works fine. I am wondering what has made this happened?

I am using r1.15 since the default TPU creation supports only 1.15 tensorflow.

**Comment by timnugent** [comment]
How did you solve this? Getting a similar error but running BERT, using 1.14, v3-8

**Comment by bittnt** [comment]
@timnugent it was my bad. In my case, I was feeding the wrong path to the tfrecords. The error message shows that when the TPU cannot find the tfrecords. It could also well be that the TPU service permission problem, the storage does not grant the permission to TPU service.

**Comment by timnugent** [comment]
Hmm that's strange, probably not the problem for me. Has already run ~60K steps (data is in a gs: bucket) which is quite a few epochs, problem must be something else. Thanks for getting back to me

**Comment by bittnt** [comment]
OK. Let me know if you resolve the problem later on. Note that I was using TF 1.15 (the default) for v3-8. I suspect that you might actually encounter that the TPU health status is bad, which can be resolved by delete the TPU and restart a new one.

**Comment by timnugent** [comment]
Ah fixed it, it was actually the same problem! However, it wasn't the training data that was missing from the storage bucket - it was the test data, so the job was actually failing right at the very end.
