### ISSUE TITLE
EfficientNet with TPU

### ISSUE THREAD

**Issue by ildoonet** [tensorflow/tpu#673]
Do we have to use efficientnet-tpu-* or efficientnet-* ?

I found that arcthiectures for TPU are diffrent than the known efficientnet architectures : https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/tpu/efficientnet_tpu_builder.py#L56

Also, it would be appreciated if I can know the exact hyperparameters of efficientnet training, since I'm having a trouble to reproduce EfficientNet result for B1 to B7. I got the similary performance for B0 model.

cc @mingxingtan

**Comment by saberkun** [comment]
No. All efficientnet variants can run on TPU.

**Comment by ildoonet** [comment]
Thanks. I will use efficient-b series.
