### ISSUE TITLE
numpy array to tfrecord

### ISSUE THREAD

**Issue by 2696120622** [tensorflow/tpu#736]
My raw data is one numpy array with shape of (H,W,C) but not read from one image like xxx.jpeg. I want to convert the numpy array to the format as the image_data= tf.gfile.FastGFile('picture.jpg', 'rb').read(). Because this fomat is required when writing the convertion result to tfrecords file. like:
      image_buffer = image_data
      example = tf.train.Example(features=tf.train.Features(feature={
      ...,
      'image/encoded': _bytes_feature(image_buffer)}))
Do you know how to do?

**Comment by liy1shu** [comment]
Hi, I also have this problem, do you know how to do it now?
