### ISSUE TITLE
Question about sacling coefficient 

### ISSUE THREAD

**Issue by ZhengfengLee** [tensorflow/tpu#738]
In this repo, i see the parameters of scaling coefficient used the value as below. 
It seems specific, but to my kownledge, width_coefficient, depth_coefficient, and so on are determined by hyperparameters \phi, \alpha, \beta, or \gamma in original paper.
I would like to know if these specfic parameters below are obtained by setting constant values (\alpha=1.2, \beta=1.1, \gamma=1.15) for efficientnet-b0, and then uniformly changing \phi. However, if that so, i can't figure out how it works to get values as belows. Hope you can answer my question.

def efficientnet_params(model_name):
  """Get efficientnet params based on model name."""
  params_dict = {
      # (width_coefficient, depth_coefficient, resolution, dropout_rate)
      'efficientnet-b0': (1.0, 1.0, 224, 0.2),
      'efficientnet-b1': (1.0, 1.1, 240, 0.2),
      'efficientnet-b2': (1.1, 1.2, 260, 0.3),
      'efficientnet-b3': (1.2, 1.4, 300, 0.3),
      'efficientnet-b4': (1.4, 1.8, 380, 0.4),
      'efficientnet-b5': (1.6, 2.2, 456, 0.4),
      'efficientnet-b6': (1.8, 2.6, 528, 0.5),
      'efficientnet-b7': (2.0, 3.1, 600, 0.5),
      'efficientnet-b8': (2.2, 3.6, 672, 0.5),
      'efficientnet-l2': (4.3, 5.3, 800, 0.5),
  }
  return params_dict[model_name]

**Comment by anhminh3105** [comment]
Hi, I'm wondering the same question. Do you have any proper answers for this already? Thanks

**Comment by ZhengfengLee** [comment]
> Hi, I'm wondering the same question. Do you have any proper answers for this already? Thanks

sorry, i still don't konw yet. can't find any helpful informations

**Comment by theDweeb** [comment]
I am also confused. The starting value for the gamma coefficient (resolution scaling) is 1.15 and the baseline image resolution is 224x224. So it makes sense that 1.15<sup>0</sup> = 1 would be the scaling factor for B0 as 224x1 = 224. EfficientNetB1 would therefore be 1.15<sup>1</sup> = 1.15 and make the resolution for B1 224x1.15 = 257.6, but in the code it shows the B1 resolution is 240, and B2 is 260. I am also confused with the other coefficients as in the code it has:

  params_dict = {
      # (width_coefficient, depth_coefficient, resolution, dropout_rate)
      'efficientnet-b0': (1.0, 1.0, 224, 0.2),
      'efficientnet-b1': (1.0, 1.1, 240, 0.2),
      'efficientnet-b2': (1.1, 1.2, 260, 0.3),
      'efficientnet-b3': (1.2, 1.4, 300, 0.3),
      'efficientnet-b4': (1.4, 1.8, 380, 0.4),
      'efficientnet-b5': (1.6, 2.2, 456, 0.4),
      'efficientnet-b6': (1.8, 2.6, 528, 0.5),
      'efficientnet-b7': (2.0, 3.1, 600, 0.5),
      'efficientnet-b8': (2.2, 3.6, 672, 0.5),
      'efficientnet-l2': (4.3, 5.3, 800, 0.5),
  }

why is β (width) coefficient for B1 = 1.0? Shouldn't it be 1.1<sup>1</sup> = 1.1? And α (depth) coefficient is 1.1 when in the paper it has α as = 1.2.
