### ISSUE TITLE
Possible Bug in EfficientNet

### ISSUE THREAD

**Issue by msalvaris** [tensorflow/tpu#751]
When running the lite version of EfficientNet on GPU I got an error due to shape mismatch. I tracked it down to here
https://github.com/tensorflow/tpu/blob/3f13f6c139698a962783397ac22a8c3ac9805201/models/official/efficientnet/efficientnet_model.py#L714

It seems that everything works fine if we use NHWC but for best performance on GPU it is recommended to do NCHW. The kernel used for the average pooling is the wrong shape I think. It is always [1,h,w,1] when for NCHW it should be [1,1,h,w]. 

I couldn't get average pooling to work with a kernel of [1,1,h,w] so stuck a couple of transformations in there and it all seems to work now. Wondering if there is a better way?

**Comment by mingxingtan** [comment]
@msalvaris Good point. the right code should be:

```
      se_tensor = tf.nn.avg_pool(
          input_tensor,
          ksize=kernel_size,
          strides=[1, 1, 1, 1],
          padding='VALID',
          data_format=self._data_format)
```

Fix will be on the next merge release. Thanks!
