### ISSUE TITLE
confusion about the TPU log

### ISSUE THREAD

**Issue by NeoZzh** [tensorflow/tpu#774]
Hi,

When using TPUs, I'm a little confused about the logs. Here is the log when doing inference:

`I0516 09:52:33.962098 140646020941568 tpu_estimator.py:567] Init TPU system
INFO:tensorflow:Initialized TPU in 16 seconds
I0516 09:52:50.222754 140646020941568 tpu_estimator.py:576] Initialized TPU in 16 seconds
INFO:tensorflow:Starting infeed thread controller.
I0516 09:52:50.241903 140643888047872 tpu_estimator.py:521] Starting infeed thread controller.
INFO:tensorflow:Starting outfeed thread controller.
I0516 09:52:50.260475 140643401725696 tpu_estimator.py:540] Starting outfeed thread controller.
INFO:tensorflow:Initialized dataset iterators in 0 seconds
I0516 09:52:50.463648 140646020941568 util.py:98] Initialized dataset iterators in 0 seconds
INFO:tensorflow:Enqueue next (1) batch(es) of data to infeed.
I0516 09:52:50.579744 140646020941568 tpu_estimator.py:600] Enqueue next (1) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (1) batch(es) of data from outfeed.
I0516 09:52:50.580183 140646020941568 tpu_estimator.py:604] Dequeue next (1) batch(es) of data from outfeed.
INFO:tensorflow:Outfeed finished for iteration (0, 0)
I0516 09:52:50.581854 140643401725696 tpu_estimator.py:279] Outfeed finished for iteration (0, 0)
INFO:tensorflow:Enqueue next (1) batch(es) of data to infeed.
I0516 09:52:59.691173 140646020941568 tpu_estimator.py:600] Enqueue next (1) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (1) batch(es) of data from outfeed.
I0516 09:52:59.691526 140646020941568 tpu_estimator.py:604] Dequeue next (1) batch(es) of data from outfeed.
`

(Please note that each line is printed twice, which is quite strange. )

It can be seen that between the first two pairs of the `Enqueue/Dequeue next (1) batch(es) ...`, one extra line, `Outfeed finished for iteration (0, 0)`, is inserted. After this line, it takes nearly **9 seconds**  to show the next `Enqueue next (1) batch(es) ...` line, which is quite long compared with the following steps in the inference stage. 

The question is: 
What does TPU actually do in these several lines? Which step consumes the 9 seconds? Loading the data iterators? And why there is still one pairs of Enqueue/Dequeue staff before the `Outfeed finished for iteration (0, 0)` line.

It is important for me to analysis the behavior and latency of TPUs during the inference. Many thanks in advance.

**Comment by ameyparanjape** [comment]
@zh-zheng So what was the real meaning of `Outfeed finished for iteration (0, 0)`? I am puzzled too!
