### ISSUE TITLE
MODEL-ZOO: Spinenet-143 Mask-RCNN ckpt is missing

### ISSUE THREAD

**Issue by mitraavi** [tensorflow/tpu#780]
Tried to download Spinenet-143 Mask-RCNN ckpt from MODEL-ZOO, I'm getting following error:

"No such object: cloud-tpu-checkpoints/detection/maskrcnn/spinenet143-mrcnn-pb.tar.gz"

**Comment by xianzhidu** [comment]
Thanks for raising this issue. You can use this link: 
https://storage.cloud.google.com/cloud-tpu-checkpoints/detection/maskrcnn/spinenet-143.tar.gz

I will update the download link soon.
