### ISSUE TITLE
Can not load ResNet checkpoint: BucketNotFoundException

### ISSUE THREAD

**Issue by Jyouhou** [tensorflow/tpu#796]
Hi, I am using this tutorial to train a mask rcnn model on GCP: https://cloud.google.com/tpu/docs/tutorials/mask-rcnn

I was able to run the training before. However, starting from a few days ago, I suddenly can no longer load the resnet checkpoint: 

export RESNET_CHECKPOINT=gs://cloud-tpu-artifacts/resnet/resnet-nhwc-2018-10-14/model.ckpt-112602
(vm)$ 

When I execute 'gsutil ls gs://cloud-tpu-artifacts', it returns BucketNotFoundException, suggesting that this bucket does not exist.

**Comment by mayefoo** [comment]
I have the same problem.

**Comment by thanhhvnqb** [comment]
I think we can download from this link: gs://cloud-tpu-checkpoints/retinanet/resnet50-checkpoint-2018-02-07

**Comment by Jyouhou** [comment]
@thanhhvnqb Thanks! It's a good idea.

**Comment by gagika** [comment]
Thanks for reporting, we have updated the tutorial with:
```
export RESNET_CHECKPOINT=gs://cloud-tpu-checkpoints/retinanet/resnet50-checkpoint-2018-02-07
```
