### ISSUE TITLE
Non TensorFlow TPU Interaction (Feature Request)

### ISSUE THREAD

**Issue by Danc2050** [tensorflow/tpu#803]
Hello,

I am not sure the difficulty of this, but It would be very neat if Google would allow interactions and any documentation of interactions with the Tensor Processing Unit (TPU) other than with the TensorFlow library.

I and a friend would like to use TPU technology but have a use case that excludes using TensorFlow due to the size of the numbers we are working with. We have not found any documentation on interacting with a TPU outside of the TensorFlow library.

We would really love to make use of a TPU and TPU Pods if at all possible. Thank you.

**Comment by swghosh** [comment]
@Danc2050 There are a few already existing implementations like [PyTorch XLA](https://github.com/pytorch/xla), [Jax](https://github.com/google/jax), [XLA for Julia](https://github.com/JuliaTPU/XLA.jl) that can well support TPUs without actually requiring the user to write TensorFlow code. Most of these implementations are based on [XLA (Accelerated Linear Algebra)](https://www.tensorflow.org/xla) which is at the core of all computations done on a TPU. But essentially, all of them are well beyond the scope of this repository.
