### ISSUE TITLE
Reinforcement Learning Example

### ISSUE THREAD

**Issue by karandwivedi42** [tensorflow/tpu#81]
Are reinforcement learning algorithms supported on the TPU? Do you plan to add examples for the same?

**Comment by saeta** [comment]
@karandwivedi42 While we definitely have numerous users doing RL on TPUs, we unfortunately still don't have a nice clean example. (To be fair, we're still improving the software stack to make it easier to do RL.) One good example we have so far is: https://github.com/tensorflow/minigo which is an extreme-scale RL environment. (There's also a talk about MiniGo from GCP NEXT at: https://www.youtube.com/watch?v=Qra8Aqxu_fo)
