### ISSUE TITLE
Accelerate inference times of pre-trained models

### ISSUE THREAD

**Issue by eriklindernoren** [tensorflow/tpu#82]
Is it possible to accelerate the inference time of a pre-trained model (e.g. from the [detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md)) with TPUs without having to adapt the model to use the estimator API?

**Comment by aman2930** [comment]
No. Currently you can't take an existing checkpoint/model and accelerate it on the TPU.
You need to use TPUEstimators.
