### ISSUE TITLE
TPU can't be used in Tensorflow v2.2.0

### ISSUE THREAD

**Issue by awsaf49** [tensorflow/tpu#823]
The same code runs fine for v2.3.0 but shows error for v2.2.0. I've tried in both Kaggle and Colab but got the same error. Check this [notebook](https://www.kaggle.com/awsaf49/tpu-error-tensorflow-v2-2-0) if you want to reproduce the result.
![can't use tpu 2](https://user-images.githubusercontent.com/36858976/90098346-d397f300-dd59-11ea-8aa2-f2af5078ae00.PNG)
![tpu can't be used](https://user-images.githubusercontent.com/36858976/90098138-608e7c80-dd59-11ea-9b10-b86143a8e713.PNG)

**Comment by gagika** [comment]
You only update Tensorflow version on client VM, TPU server still has old version of Tensorflow installed. You can use `configure_tpu_version` function to configure TPU server as well.
Could you try with the code below after you install TF 2.2?

```
!pip install cloud-tpu-client

import tensorflow as tf
from cloud_tpu_client import Client

print(tf.__version__)

Client().configure_tpu_version(tf.__version__, restart_type='ifNeeded')
```

**Comment by awsaf49** [comment]
Thanks it solved the problem!!!
