### ISSUE TITLE
MNASNET checkpoint link broken

### ISSUE THREAD

**Issue by phager90** [tensorflow/tpu#832]
The link to the MNASNET checkpoint used in this script seems broken:
https://github.com/tensorflow/tpu/blob/master/models/official/mnasnet/mnasnet_example.ipynb

Is it possible to make this checkpoint again available?
https://storage.googleapis.com/mnasnet/checkpoints/mnasnet-a1.tar.gz

**Comment by mingxingtan** [comment]
Fixed. The latest code has the right (and more) checkpoints.
