### ISSUE TITLE
how to resize image and substract mean with only tflite installed?

### ISSUE THREAD

**Issue by 2696120622** [tensorflow/tpu#836]
I convert my trained efficientnet-lite to tflite. Then, I install tflite for inference with the converted tflite model. However, the input to it should be preprocessed with  tf.image.resize_bicubic as in preprocessing.py. Without tensorflow installed, how to resize the image with only tflite?

**Comment by mingxingtan** [comment]
I believe you can do the same thing with res = cv2.resize(img, dsize, interpolation=cv2.INTER_CUBIC)
Other Image libraries (like PIL) should also have such APIs

**Comment by 2696120622** [comment]
> I believe you can do the same thing with res = cv2.resize(img, dsize, interpolation=cv2.INTER_CUBIC)
> Other Image libraries (like PIL) should also have such APIs

Thanks, I have do the same thing with scipy.misc.imresize(img,dsize,'bicubic'). However, there are a little difference for predicited probability compared to the original tf.image.resize_bicubic. Moreover, as I know, tf.image.resize_xxx will produce different resized result from cv2.resize or other image libraries like PIL.
