### ISSUE TITLE
Pass run_metadata to TPUEstimator?

### ISSUE THREAD

**Issue by Emma926** [tensorflow/tpu#84]
In order to profile the time and memory of TF workloads, according to the page below, one need to create a run_metadata = tf.RunMetadata(), and pass the run_metadata to sess.run().

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/profiler/g3doc/python_api.md

Do we have a way to pass run_metadata to TPUEstimator, or profile memory of TPU workloads in other ways?

**Comment by droidicus** [comment]
If this is still an issue, you may want to take a look at the cloud TPU tools: https://cloud.google.com/tpu/docs/cloud-tpu-tools

**Comment by qiuminxu** [comment]
Hi Emma, you can run capture_tpu_profile as a background job and write the results to your specified GCS location. As of cloud-tpu-profiler 1.9, it has a 60s upper limit in profiling duration, so you may want to write a script to periodically sample your model.

**Comment by Emma926** [comment]
Thanks @qiuminxu and @droidicus! I have managed to use capture_tpu_profile. I'm closing this issue.
