### ISSUE TITLE
tpu/tools/datasets/imagenet_to_gcs.py

### ISSUE THREAD

**Issue by aporo4000** [tensorflow/tpu#854]
@allenwang28  Hi, This change is necessary because the data cannot be retrieved.

imagenet_to_gcs.py  line350)   
validation_files = sorted(tf.gfile.Glob(
      os.path.join(raw_data_dir, VALIDATION_DIRECTORY, '*.JPEG')))
                  ↓
  validation_files = sorted(tf.gfile.Glob(
      os.path.join(raw_data_dir, VALIDATION_DIRECTORY, '\*', '*.JPEG')))

**Comment by allenwang28** [comment]
Thanks, please see https://github.com/tensorflow/tpu/pull/855/commits/c8f7747fef447fbd341b7999506a821a0d427ed4
