### ISSUE TITLE
[BUG] CTPU unable to create instance with Tensorflow version 2.4

### ISSUE THREAD

**Issue by aurelio-amerio** [tensorflow/tpu#877]
I'm using the following commands to create and launch a vm:
```
ctpu up --project=${PROJECT_ID} \
 --zone=europe-west4-a \
 --name=tpu-training \
 --tpu-size=v3-8 \
 --disk-size-gb=250
```
It default (as expected) to tf version 2.4 and the following message is printed:
```
  Name:                 tpu-training
  Zone:                 europe-west4-a
  GCP Project:          xxxxxx
  TensorFlow Version:   2.4
  VM:
      Machine Type:     n1-standard-2
      Disk Size:        250 GB
      Preemptible:      false
  Cloud TPU:
      Size:             v3-8
      Preemptible:      false
      Reserved:         false
```

One I agree to the creation of a VM and tTPU I receive the following error message:
```
googleapi: Error 400: Cloud TPU received an invalid argument. The field "TensorflowVersion" cannot be "2.4". [EID: 0x90dfdfda32f61e59], badRequest
```
and ctpu terminates.

Is Tensorflow version 2.4 not yet supported? It is listed as one of the supported versions and I've checked that TPUs on `europe-west4-a` have support for TF version 2.4.0 and there is an official TPU image for TF version 2.4, so I don't know which is the problem.

Please investigate this issue. 
TF version 2.3.1 works fine, but I need some of the new features of TF 2.4 and using the old version is not viable for me. 

Thank you for your help.

PS: I'm using the ctpu tool available on the gcp shell.

**Comment by sshahrokhi** [comment]
TF2.4 is supported. Could you add "--tf-version=2.4.0" to the command?

**Comment by aurelio-amerio** [comment]
@sshahrokhi Hello, I had tried it in the past and I've tried it right now, in this case the error I get is:
```
could not create Compute Engine instance without a base image
```
My personal understanding is that the image for Tensorflow is tagged as "2.4" and the TPU version is tagged as "2.4.0" and they don't match for some reason

**Comment by aurelio-amerio** [comment]
Any update?

**Comment by aurelio-amerio** [comment]
@sshahrokhi ctpu seems to be working correctly now if you specify "--tf-version=2.4.0"

**Comment by JulesGM** [comment]
I also get this bug if I dont specify a `--tf-version` flag because it seems to default to "2.4" and not "2.4.0"
