### ISSUE TITLE
Update EfficientNet-Lite on TFHub to TF2 SavedModel format

### ISSUE THREAD

**Issue by willbattel** [tensorflow/tpu#879]
I'm running into issues transfer-learning with the EfficientNet-Lite feature vectors provided on TFHub, which are in TF1 format. It seems that I cannot fine-tune or use a distribution strategy with TF1 models on my AI Platform 2.3 runtime. Are there any plans for updating the hub models to TF2 format? The normal EfficientNet models got this update, but the lite variants are still only TF1.

**Comment by haowang1013** [comment]
I'm having exactly the same problem, would be nice to have a fix for this soon.

**Comment by willbattel** [comment]
This issue tracker doesn't seem to be very active, so I'm closing this issue and opening a new issue here: https://github.com/tensorflow/hub/issues/751.
