### ISSUE TITLE
Resnet-50 example not working

### ISSUE THREAD

**Issue by tgrel** [tensorflow/tpu#88]
Hi, I've encountered some issues in the Resnet-50 example on a cloud TPU. I've already corrected them and will file a pull request for them in a few minutes. This issue is intended to describe the problem.

For reference I was running the resnet-50 example with a command:
`ipython2 --pdb resnet_main.py -- --tpu_name demo-tpu-3 --data_dir gs://cloud-tpu-test-datasets/fake_imagenet --model_dir gs://cloud-tpu-checkpoint-bucket/resnet50`

The first problem was in the usage of `tpu_name` parameter. It caused the script to crash because it mistook the name of the `tpu_name` (a string) for an iterable of available TPU names and started to iterate over it.

The second problem was that the reshape operation for the `global_step` variable was working on int64 dtype. This op on this dtype is not supported for TPUs, therefore the graph compilation for TPU was failing. I fixed it by casting the variable to int32 dtype and then back to int64 on CPU in order to make the summaries work.

After these corrections I'm able to successfully run the example.

**Comment by droidicus** [comment]
The change to the ```tpu_name``` parameter looks like it is valid in TF v1.7.0-rc0, but is causing the issue described in v1.6.0.

**Comment by jhseu** [comment]
The master branch may not be compatible with v1.6.0. Please use the r1.6 branch for a TF 1.6-compatible version of the models. We load that branch automatically onto the VM image.
