### ISSUE TITLE
still no proper MobileNetV3 implementation

### ISSUE THREAD

**Issue by ghylander** [tensorflow/tpu#886]
this was originally raised back in issue #522 ,over a year ago

The MobileNetV3 implementation does not make use of the 5x5 convolution or the hard swish activation functions

are there any plans to implement this, at any moment in time? 

if not, is there any plan to at least implement the hard swish function?

running tf-nightly (2.5.x) and there is no trace of either

**Comment by 8bitmp3** [comment]
> The MobileNetV3 implementation

@ghylander After doing a quick search in other repos, I found this in `google-research`:

https://github.com/google-research/deeplab2/blob/main/model/encoder/mobilenet.py

> the hard swish function

https://github.com/google-research/deeplab2/blob/43979b08f4d858b0b988340400b3bb5844a89f86/model/layers/activations.py#L76

```python
def hard_swish(input_tensor):
  """Hard Swish function.
  Args:
    input_tensor: A tensor with an arbitrary shape.
  Returns:
    The activated input tensor.
  """
  input_tensor = tf.convert_to_tensor(input_tensor)
  return input_tensor * tf.nn.relu6(
      input_tensor + tf.constant(3.)) * (1. / 6.)
```

> the 5x5 convolution

https://github.com/google-research/deeplab2/blob/main/model/layers/convolutions.py

Can you check if it's there? cc @MarkDaoust
