### ISSUE TITLE
ctpu version issues

### ISSUE THREAD

**Issue by droidicus** [tensorflow/tpu#91]
Currently, when I query the available versions with ctpu, I get the following output:
```
$ ctpu tf-versions
2018/03/13 14:24:49 WARNING: Setting zone to "us-central1-c"
Cloud TPU TensorFlow Versions:
        1.7     (default version)
        1.6
```

if I then attempt to start a flock the following error is generated:
```
$ ctpu up
2018/03/13 14:34:07 WARNING: Setting zone to "us-central1-c"
2018/03/13 14:34:08 Creating GCE VM first-last(this may take a minute)...
2018/03/13 14:34:08 Creating TPU first-last (this may take a few minutes)...
2018/03/13 14:34:08 could not create GCE Instance without a base image
```

Also, when starting a new flock with ```$ ctpu up -tf-version=1.6``` the version of TF on the resulting VM is ```1.6.0-rc0```, not the latest release version.

**Comment by saeta** [comment]
Hey! Sorry about that, we're working on the TF 1.7 release, but got our configuration a little messed up. Sorry about that. We noticed that our TF 1.6 GCE VM images stopped building a bit ago, and have a fix for that rolling out shortly, and we'll update our configs to pull back TF 1.7 until at minimum we have the corresponding GCE VM image ready as well. Thank you for your patience on this!

**Comment by droidicus** [comment]
No problem, thanks again.

**Comment by saeta** [comment]
Hey @droidicus this should now be resolved. (We pulled back 1.7, got the GCE images properly created, and re-enabled 1.7.) Please let me know if you see any further issues. Thanks!
