### ISSUE TITLE
script link mentioned in tpu/models/official/resnet/README.md is not accessible

### ISSUE THREAD

**Issue by yongcale** [tensorflow/tpu#95]
The link(https://github.com/tensorflow/tpu/blob/master/cloud_tpu/datasets/imagenet_to_gcs.py) in tpu/models/official/resnet/README.md is not accessible, seems the page is removed, please update it. Maybe this one -https://raw.githubusercontent.com/tensorflow/tpu/master/tools/datasets/imagenet_to_gcs.py ?

**Comment by saeta** [comment]
Hey @yongcale ! Thanks for pointing this out. I'll be updating the README link shortly. -Brennan

**Comment by rxsang** [comment]
The link in README points to the valid script now.
